\sloppy
\newpage
* Meta-data                                                        :noexport:
#+TITLE:
#+AUTHOR:
#+OPTIONS: ^:{}
# LATEX configurations
#+LATEX_CLASS_OPTIONS: [dvipdfmx,10pt]
#+LATEX_HEADER: %% Margin
#+LATEX_HEADER: %% \usepackage[margin=1.5cm]{geometry}
#+LATEX_HEADER: \usepackage[top=2cm, bottom=2cm, left=2cm, right=2cm, headsep=4pt]{geometry}
#+LATEX_HEADER: %% \addtolength{\topmargin}{0.3cm}
#+LATEX_HEADER: %% \addtolength{\textheight}{1.75in}
#+LATEX_HEADER: %% Math
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER: %% Allow new page within align
#+LATEX_HEADER: \allowdisplaybreaks
#+LATEX_HEADER: \usepackage{cancel}
#+LATEX_HEADER: % % Code
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{courier}
#+LATEX_HEADER: \lstset{basicstyle=\footnotesize\ttfamily, breaklines=true, frame=single}
#+LATEX_HEADER: \usepackage[cache=false]{minted}
#+LATEX_HEADER: \usemintedstyle{vs}
#+LATEX_HEADER: %% Graphics
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{grffile}
#+LATEX_HEADER: %% DAG
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{positioning,shapes.geometric}
#+LATEX_HEADER: %% Date
#+LATEX_HEADER: \usepackage[yyyymmdd]{datetime}
#+LATEX_HEADER: \renewcommand{\dateseparator}{--}
#+LATEX_HEADER: %% Header
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{} % Erase first to supress section names
#+LATEX_HEADER: \fancyhead[L]{K Yoshida, et al.} % LEFT
#+LATEX_HEADER: \fancyhead[C]{Supplement} % CENTER
#+LATEX_HEADER: \fancyhead[R]{\today} % RIGHT
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: %% \fancyfoot[R]{Page \thepage\ of \pageref{LastPage}}
#+LATEX_HEADER: %% Section font size
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \sectionfont{\small}
#+LATEX_HEADER: \subsectionfont{\small}
#+LATEX_HEADER: \subsubsectionfont{\small}
#+LATEX_HEADER: %% Section numbering
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/3177/how-to-change-the-numbering-of-part-chapter-section-to-alphabetical-r
#+LATEX_HEADER: %% \renewcommand\thesection{\alph{section}}
#+LATEX_HEADER: %% \renewcommand\thesubsection{\thesection.\arabic{subsection}}
#+LATEX_HEADER: %% \renewcommand{\thesubsubsection}{\thesubsection.\alph{subsubsection}}
#+LATEX_HEADER: %%
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/40067/numbering-sections-with-sequential-integers
#+LATEX_HEADER: %% \usepackage{chngcntr}
#+LATEX_HEADER: %% \counterwithout{subsection}{section}
#+LATEX_HEADER: %% enumerate
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: %% double space
#+LATEX_HEADER: %% \usepackage{setspace}
#+LATEX_HEADER: %% \linespread{2}
#+LATEX_HEADER: %% Paragraph Indentation
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \setlength{\parindent}{0em}
#+LATEX_HEADER: %% Spacing after headings
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/53338/reducing-spacing-after-headings
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titlespacing      \section{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: \titlespacing   \subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: \titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: %% Fix figures and tables by [H]
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: %% Allow URL embedding
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage{fontawesome}
#+LATEX_HEADER: \input{\string~/.emacs.d/misc/GrandMacros}
# ############################################################################ #

* Brief description of the causal mediation analysis

The literature on the causal mediation is vast cite:vanderweeleExplanationCausalInference2015 and is evolving, thus, only the pieces relevant for the current software are reviewed here.

** Decomposition of total effect
Let $Y$ be the outcome variable of interest, $A$ be the treatment variable of interest, $M$ be the mediator variable of interest, and $\bC$ be the potentially vector-valued pre-treatment baseline covariates necessary for exchangeability. The treatment contrast of interest is $a_{1}$ vs $a_{0}$, the second being the reference level. The counterfactual $Y_{a,m}$ is the value of $Y$ for an individual when, possibly contrary to the fact, the treatment level $a$ and mediator level $m$ are assigned.\\

Given these notations, the effects are defined as follows at the covariate level $\bC = \bc$ and the mediator level $M = m$ (only for CDE).

\begin{align*}
TE &= E[Y_{a_{1}} | \bC = \bc] - E[Y_{a_{0}} | \bC = \bc]\\
\\
CDE(m) &= E[Y_{a_{1},m} | \bC = \bc] - E[Y_{a_{0},m} | \bC = \bc]\\
\\
TNIE &= E[Y_{a_{1},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{1},M_{a_{0}}} | \bC = \bc]\\
PNDE &= E[Y_{a_{1},M_{a_{0}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
\\
TNDE &= E[Y_{a_{1},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{1}}} | \bC = \bc]\\
PNIE &= E[Y_{a_{0},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
\end{align*}

The total effect (TE) can be decomposed into the direct (non-mediated) effect and indirect (mediated) effect in two different ways cite:robinsIdentifiabilityExchangeabilityDirect1992,vanderweeleThreewayDecompositionTotal2013.\\

 The decomposition of TE into the pure (natural) direct effect (PNDE) and the total (natural) indirect effect (TNIE) is the usual decomposition cite:pearlDirectIndirectEffects2001.

\begin{align*}
TNIE &= E[Y_{a_{1},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{1},M_{a_{0}}} | \bC = \bc]\\
PNDE &= E[Y_{a_{1},M_{a_{0}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
\end{align*}

 The other decomposition of TE is into the pure (natural) indirect effect (PNIE) and the total (natural) direct effect (TNDE) cite:robinsIdentifiabilityExchangeabilityDirect1992.

\begin{align*}
TNDE &= E[Y_{a_{1},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{1}}} | \bC = \bc]\\
PNIE &= E[Y_{a_{0},M_{a_{1}}} | \bC = \bc] - E[Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
\end{align*}

 These decomposition differs in the cross-world counterfactual state that is used as the partition. The PNDE+TNIE decomposition uses $Y_{a_{1},M_{a_{0}}}$ (treatment exerting on the outcome changes first), whereas the PNIE+TNDE decomposition uses $Y_{a_{0},M_{a_{1}}}$ (treatment exerting on the mediator changes first). In either case, the effect that has the reference counterfactual outcome $Y_{a_{0}} = Y_{a_{0},M_{0}}$ is the "pure" effect and the effect that has $Y_{a_{1}} = Y_{a_{1},M_{1}}$ is the total effect. See cite:vanderweeleThreewayDecompositionTotal2013 for the meaning of these two decompositions.\\

More in general, we can consider the effects on the link function scale as follows cite:starkopfComparisonFiveSoftware2017.

\begin{align*}
TE &= g(E[Y_{a_{1}} | \bC = \bc]) - g(E[Y_{a_{0}} | \bC = \bc])\\
\\
CDE(m) &= g(E[Y_{a_{1},m} | \bC = \bc]) - g(E[Y_{a_{0},m} | \bC = \bc])\\
\\
TNIE &= g(E[Y_{a_{1},M_{a_{1}}} | \bC = \bc]) - g(E[Y_{a_{1},M_{a_{0}}} | \bC = \bc])\\
PNDE &= g(E[Y_{a_{1},M_{a_{0}}} | \bC = \bc]) - g(E[Y_{a_{0},M_{a_{0}}} | \bC = \bc])\\
\\
TNDE &= g(E[Y_{a_{1},M_{a_{1}}} | \bC = \bc]) - g(E[Y_{a_{0},M_{a_{1}}} | \bC = \bc])\\
PNIE &= g(E[Y_{a_{0},M_{a_{1}}} | \bC = \bc]) - g(E[Y_{a_{0},M_{a_{0}}} | \bC = \bc])\\
\end{align*}


* Understanding the approach
Here we describe the formulas implemented in =regmendint=, using the notational convention in cite:vanderweeleExplanationCausalInference2015,valeriMediationAnalysisAllowing2013,valeriSASMacroCausal2015.

** Parametrizing the mediation formulas
The method directly parametrize the effects with the coefficients of the mediator model ($\beta$) and the outcome model ($\theta$). The maximum likelihood estimates (MLE) of these effects are the ones with these parameters replaced with their respective MLEs. See XYZ for derivation of these formulas.\\

*** Linear mediator model, linear outcome model
The function =calc_myreg_mreg_linear_yreg_linear_est()= implements the effect formulas in cite:vanderweeleExplanationCausalInference2015 (p466).

\begin{align*}
  &\text{Models}\\
  E[Y|A=a,M=m,\bC=\bc] &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc\\
  E[M|A=a,\bC=\bc] &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc\\
  \\
  &\text{Effects}\\
  CDE(m) &= E[Y_{a_{1},m} - Y_{a_{0},m} | \bC = \bc]\\
  &= (\theta_{1} + \theta_{3}m)(a_{1} - a_{0})\\
  \\
  PNDE &= E[Y_{a_{1},M_{a_{0}}} - Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc) \right\} (a_{1} - a_{0})\\
  TNIE &= E[Y_{a_{1},M_{a_{1}}} - Y_{a_{1},M_{a_{0}}} | \bC = \bc]\\
  &= \beta_{1}(\theta_{2} + \theta_{3}a_{1})(a_{1} - a_{0})\\
  \\
  TNDE &= E[Y_{a_{1},M_{a_{1}}} - Y_{a_{0},M_{a_{1}}} | \bC = \bc]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc) \right\} (a_{1} - a_{0})\\
  PNIE &= E[Y_{a_{0},M_{a_{1}}} - Y_{a_{0},M_{a_{0}}} | \bC = \bc]\\
  &= \beta_{1}(\theta_{2} + \theta_{3}a_{0})(a_{1} - a_{0})\\
  \\
  TE &= PNDE + TNIE\\
  PM &= \frac{TNIE}{PNDE + TNIE}\\
\end{align*}

** Obtaining standard errors via multivariate delta method

As seen above, each effects of interest is estimated as a scalar-valued, non-linear function of estiamted coefficients for the mediator model and the outcome model. Thus, we can obtain the standard error of each effect estimate using the variance covariance matrix for the coefficients and multivariate delta method cite:hoefWhoInventedDelta2012.\\

Let the scalar quantity of interest be $Q$, a function of parameter vector $(\bbeta^{T},\btheta^{T})^{T}$. Then, its gradient (vector of partial derivatives) with respect to the parameter vector $(\bbeta^{T},\btheta^{T})^{T}$ is the following.\\

\begin{align*}
\nabla Q &= \frac{\partial Q}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
         &= \begin{bmatrix}
           \frac{\partial Q}{\partial \beta_{0}}\\
           \vdots\\
           \frac{\partial Q}{\partial \beta_{2}}\\
           \frac{\partial Q}{\partial \theta_{0}}\\
           \vdots\\
           \frac{\partial Q}{\partial \theta_{4}}\\
         \end{bmatrix}\\
\end{align*}

By the large sample approximation using the multivariate delta method, the variance of the quantity of interest evaluated at the MLEs $(\bbetahat^{T},\bthetahat^{T})^{T}$ is the following.

\begin{align*}
  \underbrace{Var \left[ Q\left\{ (\bbetahat^{T},\bthetahat^{T})^{T} \right\} \right]}_{\text{scalar}}
  &\approx
  \underbrace{\left[ \nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right) \right]^{T}}_{\text{row vector}}
  \underbrace{Var((\bbetahat^{T},\bthetahat^{T})^{T})}_{\text{matrix}}
  \underbrace{\left[ \nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right) \right]}_{\text{column vector}}
\end{align*}

This expression is abbreviated as $\Gamma\Sigma\Gamma'$ in cite:vanderweeleExplanationCausalInference2015,valeriMediationAnalysisAllowing2013,valeriSASMacroCausal2015. In these references, the treatment contrast ($a_{1}-a_{0}$) is factored out from $\nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right)$ when possible.


*** Linear mediator model, linear outcome model
The function =calc_myreg_mreg_linear_yreg_linear_se()= implements the standard error formulas in cite:vanderweeleExplanationCausalInference2015 (p466).

\begin{align*}
  (a_{1}-a_{0})\Gamma_{CDE(m)}
  &= \frac{\partial CDE(m)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      0\\
      \b0\\
      0\\
      1\\
      0\\
      m\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{PNDE}
  &= \frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}a_{0}\\
      \theta_{3}\bc\\
      0\\
      1\\
      0\\
      \beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc\\
      \b0\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{TNIE}
  &= \frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}a_{1}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}a_{1}\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TNDE}
  &= \frac{\partial TNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}a_{1}\\
      \theta_{3}\bc\\
      0\\
      1\\
      0\\
      \beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc\\
      \b0\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{PNIE}
  &= \frac{\partial PNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}a_{0}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}a_{0}\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TE}
  &= \frac{\partial TE}{\partial (\bbeta^{T},\btheta^{T})^{T}} = \frac{\partial (PNDE+TNIE)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})(\Gamma_{PNDE} + \Gamma_{TNIE})\\
  \\
  (a_{1}-a_{0})\Gamma_{PM}
  &= \frac{\partial PM}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &~~~\text{By multivariate chain rule}\\
  &= \frac{\partial PM}{\partial PNDE}\frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}} + \frac{\partial PM}{\partial TNIE}\frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial PM}{\partial PNDE}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{\partial PM}{\partial TNIE}(a_{1}-a_{0})\Gamma_{TNIE}\\
  &= \frac{-TNIE}{(PNDE+TNIE)^{2}}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{PNDE}{(PNDE+TNIE)^{2}}(a_{1}-a_{0})\Gamma_{TNIE}\\
  &= (a_{1}-a_{0}) \frac{-TNIE~\Gamma_{PNDE} + PNDE~\Gamma_{TNIE}}{(PNDE+TNIE)^{2}}\\
\end{align*}


* Software
The detailed explanation of the software implementation is given on its website (https://kaz-yos.github.io/regmedint/index.html).

* Bibliography
\renewcommand{\section}[2]{}
# Following lines must be left-aligned without preceding spaces.
bibliographystyle:apalike
bibliography:~/.emacs.d/misc/zotero.bib
