\sloppy
\setcounter{page}{0}
\newpage
\setcounter{section}{-1}
* Meta-data                                                        :noexport:
#+TITLE:
#+AUTHOR:
#+OPTIONS: ^:{}
# LATEX configurations
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: %% Margin
#+LATEX_HEADER: %% \usepackage[margin=1.5cm]{geometry}
#+LATEX_HEADER: \usepackage[top=2cm, bottom=2cm, left=2cm, right=2cm, headsep=4pt]{geometry}
#+LATEX_HEADER: %% \addtolength{\topmargin}{0.3cm}
#+LATEX_HEADER: %% \addtolength{\textheight}{1.75in}
#+LATEX_HEADER: %% Math
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER: %% Allow new page within align
#+LATEX_HEADER: \allowdisplaybreaks
#+LATEX_HEADER: \usepackage{cancel}
#+LATEX_HEADER: % % Code
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{courier}
#+LATEX_HEADER: \lstset{basicstyle=\footnotesize\ttfamily, breaklines=true, frame=single}
#+LATEX_HEADER: \usepackage[cache=false]{minted}
#+LATEX_HEADER: \usemintedstyle{vs}
#+LATEX_HEADER: %% Graphics
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{grffile}
#+LATEX_HEADER: %% DAG
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{positioning,shapes.geometric}
#+LATEX_HEADER: %% Date
#+LATEX_HEADER: \usepackage[yyyymmdd]{datetime}
#+LATEX_HEADER: \renewcommand{\dateseparator}{--}
#+LATEX_HEADER: %% Header
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{} % Erase first to supress section names
#+LATEX_HEADER: \fancyhead[L]{K Yoshida, et al.} % LEFT
#+LATEX_HEADER: \fancyhead[C]{Supplement} % CENTER
#+LATEX_HEADER: \fancyhead[R]{\today} % RIGHT
#+LATEX_HEADER: \fancyfoot[C]{\thepage}
#+LATEX_HEADER: %% \fancyfoot[R]{Page \thepage\ of \pageref{LastPage}}
#+LATEX_HEADER: %% Section font size
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \sectionfont{\small}
#+LATEX_HEADER: \subsectionfont{\small}
#+LATEX_HEADER: \subsubsectionfont{\small}
#+LATEX_HEADER: %% Section numbering
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/3177/how-to-change-the-numbering-of-part-chapter-section-to-alphabetical-r
#+LATEX_HEADER: %% \renewcommand\thesection{\alph{section}}
#+LATEX_HEADER: %% \renewcommand\thesubsection{\thesection.\arabic{subsection}}
#+LATEX_HEADER: %% \renewcommand{\thesubsubsection}{\thesubsection.\alph{subsubsection}}
#+LATEX_HEADER: %%
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/40067/numbering-sections-with-sequential-integers
#+LATEX_HEADER: %% \usepackage{chngcntr}
#+LATEX_HEADER: %% \counterwithout{subsection}{section}
#+LATEX_HEADER: %% enumerate
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: %% double space
#+LATEX_HEADER: %% \usepackage{setspace}
#+LATEX_HEADER: %% \linespread{2}
#+LATEX_HEADER: %% Paragraph Indentation
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \setlength{\parindent}{0em}
#+LATEX_HEADER: %% Spacing after headings
#+LATEX_HEADER: %% http://tex.stackexchange.com/questions/53338/reducing-spacing-after-headings
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titlespacing      \section{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: \titlespacing   \subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: \titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
#+LATEX_HEADER: %% Fix figures and tables by [H]
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: %% Allow URL embedding
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: % Required for XeLaTeX. Also install FontAwesome.otf system-wide.
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{fontawesome}
#+LATEX_HEADER: %% https://github.com/kaz-yos/emacs/blob/master/misc/GrandMacros.tex
#+LATEX_HEADER: \input{\string~/.emacs.d/misc/GrandMacros}
# ############################################################################ #

* Overview of the supplement document

This supplement document provides additional details for the causal mediation analysis method implemented in the =R= package [[https://kaz-yos.github.io/regmedint/][=regmedint=]] (https://kaz-yos.github.io/regmedint/). The sections cover the following topics.\\

[[* Brief description of causal mediation analysis]]. Definitions of the causal quantities interest and assumptions required for their identification.\\
[[* Implementation of the regression-based causal mediation analysis method]]. Outline of the estimation method implemented in =regmedint= and mathematical formulas.\\
[[* Software user guide and reproducible code]]. Links to software guide for =regmedint= and code to reproduce the example.\\
[[* Demonstration of covariate-dependence of natural effect estimates]]. Visual demonstration of covariate-dependence of effect estimates.\\

Applied users of the =regmedint= package should benefit most from the sotware instructions in Section [[* Software user guide and reproducible code]] and the causal assumptions stated in Section [[* Brief description of causal mediation analysis]]. Section [[* Implementation of the regression-based causal mediation analysis method]] is meant for methodologists and developers looking for the implementation details of the =regmedint= package.\\

Section [[* Demonstration of covariate-dependence of natural effect estimates]] visually demonstrate a somewhat overlooked aspect of the regression-based causal mediation analysis using an added functionality of the =regmedint= package (re-evaluation of effect estimates at various covariate levels without model refitting). Practical implications for reporting are discussed.\\

The latest version of this supplement document as well as the corresponding =org-mode= and \LaTeX \nbsp{} documents can be found at: https://github.com/kaz-yos/regmedint-supplement.


* Brief description of causal mediation analysis
The literature on causal mediation analysis is vast cite:vanderweeleExplanationCausalInference2015 and is evolving, thus, only the pieces relevant for the current software are reviewed here.

** Decomposition of total effect
Let $Y$ be the outcome variable of interest, $A$ be the treatment variable of interest, $M$ be the mediator variable of interest, and $\bC$ be the potentially vector-valued pre-treatment baseline covariates necessary for exchangeability (See the section on identification). The treatment contrast of interest is $a_{1}$ vs $a_{0}$, the second being the reference level. The counterfactual $Y_{a,m}$ is the value of $Y$ for an individual when, possibly contrary to the fact, the treatment level $a$ and mediator level $m$ are assigned.\\

The total effect (TE), the causal effect of chaning the treatment level from the reference level $a_{0}$ to the level of interest $a_{1}$, is defined as follows at the covariate level $\bC = \bc$.

\begin{align*}
  TE &= E[Y_{a_{1}} | \bC = \bc] - E[Y_{a_{0}} | \bC = \bc]
\end{align*}

The conditional direct effect (CDE(m)), the effect of chaning the treatment level from the reference level $a_{0}$ to the level of interest $a_{1}$ while fixing the mediator at $m$ is the following at the covariate level $\bC = \bc$.

\begin{align*}
  CDE(m) &= E[Y_{a_{1},m} | \bC = \bc] - E[Y_{a_{0},m} | \bC = \bc]
\end{align*}

The TE can be decomposed into the direct (non-mediated) effect and indirect (mediated) effect in two different ways cite:robinsIdentifiabilityExchangeabilityDirect1992,vanderweeleThreewayDecompositionTotal2013.\\

The decomposition of TE into the pure natural direct effect (PNDE) and the total natural indirect effect (TNIE) is the usual decomposition cite:pearlDirectIndirectEffects2001. Note that the treatment value indexing the mediator $M$ is fixed at $a_{0}$ in the PNDE, whereas the treatment value indexing the outcome $Y$ is fixed at $a_{1}$ in the TNIE. These are emphasized with $\uwave{~~~~}$ throughout the document.

\begin{align*}
  PNDE &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  TNIE &= E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc]\\
\end{align*}

 The other decomposition of TE is into the pure natural indirect effect (PNIE) and the total natural direct effect (TNDE) cite:robinsIdentifiabilityExchangeabilityDirect1992. Note that the treatment value indexing the mediator $M$ is fixed at $a_{1}$ in the TNDE, whereas the treatment value indexing the outcome $Y$ is fixed at $a_{0}$ in the PNIE. That is, these flipped in this decomposition. These are emphasized with $\uwave{~~~~}$ throughout the document.

\begin{align*}
  TNDE &= E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc]\\
  PNIE &= E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc]\\
\end{align*}

More intuitively, these decomposition differs in the cross-world counterfactual state that is used as the partition. The usual PNDE+TNIE decomposition uses $Y_{a_{1},M_{a_{0}}}$ (treatment indexing on the outcome goes up to $a_{1}$ from $a_{0}$ first), whereas the PNIE+TNDE decomposition uses $Y_{a_{0},M_{a_{1}}}$ (treatment indexing the mediator goes up to $a_{1}$ from $a_{0}$ first).\\

 In either case, the effect that has the reference counterfactual outcome $Y_{a_{0}} = Y_{a_{0},M_{a_{0}}}$ is the /pure/ natural direct/indirect effect and the effect that has $Y_{a_{1}} = Y_{a_{1},M_{a_{1}}}$ is the /total/ natural direct/indirect effect. See cite:vanderweeleThreewayDecompositionTotal2013 for the meaning of these two decompositions in terms of causal interaction.\\

More in general, we can consider the effects on the outcome model link function ($g_{Y}$) scale as follows cite:starkopfComparisonFiveSoftware2017.

\begin{align*}
  TE &= g_{Y}(E[Y_{a_{1}} | \bC = \bc]) - g_{Y}(E[Y_{a_{0}} | \bC = \bc])\\
  \\
  CDE(m) &= g_{Y}(E[Y_{a_{1},m} | \bC = \bc]) - g_{Y}(E[Y_{a_{0},m} | \bC = \bc])\\
  \\
  PNDE &= g_{Y}(E[Y_{a_{1},M_{a_{0}}} | \bC = \bc]) - g_{Y}(E[Y_{a_{0},M_{a_{0}}} | \bC = \bc])\\
  TNIE &= g_{Y}(E[Y_{a_{1},M_{a_{1}}} | \bC = \bc]) - g_{Y}(E[Y_{a_{1},M_{a_{0}}} | \bC = \bc])\\
  \\
  TNDE &= g_{Y}(E[Y_{a_{1},M_{a_{1}}} | \bC = \bc]) - g_{Y}(E[Y_{a_{0},M_{a_{1}}} | \bC = \bc])\\
  PNIE &= g_{Y}(E[Y_{a_{0},M_{a_{1}}} | \bC = \bc]) - g_{Y}(E[Y_{a_{0},M_{a_{0}}} | \bC = \bc])\\
\end{align*}


** Identification of natural effects
Several conditional exchangeabilities must be assumed for identification of effects in the causal mediation framework. See cite:vanderweeleExplanationCausalInference2015 (p463) for details.

\begin{align*}
  &\text{A1}\\
  Y_{a,m} &\ind A | \bC\\
  &\text{A2}\\
  Y_{a,m} &\ind M | \left\{ A, \bC \right\}\\
  &\text{A3}\\
  M_{a} &\ind A | \bC\\
  &\text{A4}\\
  Y_{a,m} &\ind M_{a^{*}} |\bC\\
\end{align*}

The controlled direct effect (CDE) is identified with only Assumptions A1 and A2. The natural effects require all four assumptions.  Intuitively, the identification of CDE involves handling the treatment and the mediator as a sequence of exposures, whose causal effects on the outcome must be identified. Thus, the conditional exchangeabilities for the treatment as an exposure (A1) and the mediator as an exposure (A2) are required.\\

Additionally, the identification of the natural effects require identifying the causal effect of the treatment on the mediator acting as an "outcome" (thus, Assumption A3). The identification of the partitioning counterfactual state mentioned above, in which the treatment value indexing the outcome $Y$ and the treatment value indexing the mediator $M$ differ requires Assumption A4.\\

Given these four assumptions, the mean counterfactual with different treatment values indexing the outcome $Y$ and the mediator $M$ can be identified as follows. See cite:vanderweeleExplanationCausalInference2015 (p465) for the proof. For a continuous $M$, the summation is replaced with an integration.

\begin{align*}
  &~~~\text{By iterative expectation}\\
  E[Y_{a,M_{a^{*}}} | \bC = \bc]
  &= E \left[ E[Y_{a,M_{a^{*}}} | M_{a^{*}}, \bC = \bc] | \bC = \bc \right]\\
  &~~~\text{Rewrite outer expectation as Riemann-Stieltjes integral}\\
  &= \int_{m} E[Y_{a,M_{a^{*}}} | M_{a^{*}} = m, \bC = \bc] \mathrm{d}F(M_{a^{*}} = m | \bC = \bc) \\
  &~~~\because~ M_{a^{*}} = m\\
  &= \int_{m} E[Y_{a,m} | M_{a^{*}} = m, \bC = \bc] \mathrm{d}F(M_{a^{*}} = m | \bC = \bc) \\
  &~~~\because~ \text{A4. } Y_{a,m} \ind M_{a^{*}} |\bC\\
  &= \int_{m} E[Y_{a,m} | \bC = \bc] \mathrm{d}F(M_{a^{*}} = m | \bC = \bc) \\
  &~~~\because~ \text{A3. } M_{a} \ind A | \bC\\
  &= \int_{m} E[Y_{a,m} | \bC = \bc] \mathrm{d}F(M_{a^{*}} = m | A, \bC = \bc) \\
  &~~~\because~ \text{Any given $A$ is equivalent, use stratum }a^{*}\\
  &= \int_{m} E[Y_{a,m} | \bC = \bc] \mathrm{d}F(M_{a^{*}} = m | A = a^{*}, \bC = \bc) \\
  &~~~\text{By causal consistency for }M\\
  &= \int_{m} E[Y_{a,m} | \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc) \\
  &~~~\because~ \text{A1. } Y_{a,m} \ind A | \bC\\
  &= \int_{m} E[Y_{a,m} | A, \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc) \\
  &~~~\because~ \text{Any given $A$ is equivalent, use stratum }a\\
  &= \int_{m} E[Y_{a,m} | A = a, \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc) \\
  &~~~\because~ \text{A3. } Y_{a,m} \ind M | \left\{ A, \bC \right\}\\
  &= \int_{m} E[Y_{a,m} | A = a, M, \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc) \\
  &~~~\because~ \text{Any given $M$ is equivalent, use stratum }m\\
  &= \int_{m} E[Y_{a,m} | A = a, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc) \\
  &~~~\text{By causal consistency for }Y\\
  &= \int_{m} E[Y | A = a, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a^{*}, \bC = \bc)\\
  &~~~\text{Written in terms of expectation}\\
  &= E \left[ E[Y | A = a, M, \bC = \bc] | A = a^{*}, \bC = \bc \right]\\
\end{align*}

We can observe that the first treatment value $a$ in the counterfactual $Y_{\uwave{a},M_{a^{*}}}$ indexes the outcome model $E[Y | A = \uwave{a}, M = m, \bC = \bc]$, whereas the second treatment value $a^{*}$ in the counterfactual $Y_{a,\uwave{M_{a^{*}}}}$ indexes the mediator model $P(M = m | A = \uwave{a^{*}}, \bC = \bc)$.\\

Thus, this expression takes the expectation of the inner expectation, $Y$ given $(a,m,\bc)$ (seen as a function of $m$ only), using the distribution of $M$ given $(a^{*},\bc)$.\\

The identification formulas for the two natural /direct/ effects are the following. Note the change in the treatment value indexing the /mediator model/ from $a_{0}$ in the PNDE (usual NDE) to $a_{1}$ in the TNDE (annotated with \uwave{~~~~}). Within each effect, only the treatment values indexing the /outcome model/ vary (ones not annotated) because each NDE represent the direct effect of the treatment when the mediator is fixed at the natural value it would take under one treatment value (annotated with \uwave{~~~~}).

\begin{align*}
  PNDE
  &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  &=     \int_{m} E[Y | A = a_{1}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = \uwave{a_{0}}, \bC = \bc)\\
  &~~~ - \int_{m} E[Y | A = a_{0}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = \uwave{a_{0}}, \bC = \bc)\\
  &= \int_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times \mathrm{d}F(M = m | A = \uwave{a_{0}}, \bC = \bc)\\
  &= \left\{
  \begin{aligned}
  &~~~\text{For continuous }M\\
  &\int_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times f(M = m | A = \uwave{a_{0}}, \bC = \bc) \mathrm{d}m\\
  &\\
  &~~~\text{For discrete }M\\
  &\sum_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times P(M = m | A = \uwave{a_{0}}, \bC = \bc)\\
  \end{aligned}
\right .\\
  \\
  TNDE
  &= E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc]\\
  &=     \int_{m} E[Y | A = a_{1}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = \uwave{a_{1}}, \bC = \bc)\\
  &~~~ - \int_{m} E[Y | A = a_{0}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = \uwave{a_{1}}, \bC = \bc)\\
  &= \int_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times \mathrm{d}F(M = m | A = \uwave{a_{1}}, \bC = \bc)\\
  &= \left\{
  \begin{aligned}
  &~~~\text{For continuous }M\\
  &\int_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times f(M = m | A = \uwave{a_{1}}, \bC = \bc) \mathrm{d}m\\
  &\\
  &~~~\text{For discrete }M\\
  &\sum_{m} \left\{ E[Y | A = a_{1}, M = m, \bC = \bc] - E[Y | A = a_{0}, M = m, \bC = \bc] \right\}\\
  &~~~ \times f(M = m | A = \uwave{a_{1}}, \bC = \bc)\\
  \end{aligned}
\right .\\
\end{align*}

The identification formulas for the two natural /indirect/ effects are the following. Note the change in the treatment value indexing the /outcome model/ from $a_{1}$ in the TNIE (usual NIE) to $a_{0}$ in the PNIE (annotated with \uwave{~~~~}). Within each effect, only the treatment values indexing the /mediator model/ vary (ones not annotated) because each NIE represent the indirect effect of the treatment when its effect on the mediator is "turned on", while the treatment value representing the direct path is fixed at the natural value it would take under one treatment value (annotated with \uwave{~~~~}).

\begin{align*}
  TNIE
  &= E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc]\\
  &=     \int_{m} E[Y | A = \uwave{a_{1}}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a_{1}, \bC = \bc)\\
  &~~~ - \int_{m} E[Y | A = \uwave{a_{1}}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a_{0}, \bC = \bc)\\
  &= \int_{m} E[Y | A = \uwave{a_{1}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ \mathrm{d}F(M = m | A = a_{1}, \bC = \bc) - \mathrm{d}F(M = m | A = a_{0}, \bC = \bc) \right\}\\
  &= \left\{
  \begin{aligned}
  &~~~\text{For continuous }M\\
  &\int_{m} E[Y | A = \uwave{a_{1}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ f(M = m | A = a_{1}, \bC = \bc) - f(M = m | A = a_{0}, \bC = \bc) \right\} \mathrm{d}m\\
  &\\
  &~~~\text{For discrete }M\\
  &\sum_{m} E[Y | A = \uwave{a_{1}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ P(M = m | A = a_{1}, \bC = \bc) - P(M = m | A = a_{0}, \bC = \bc) \right\}\\
  \end{aligned}
\right .\\
  \\
  PNIE
   &= E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc]\\
  &=     \int_{m} E[Y | A = \uwave{a_{0}}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a_{1}, \bC = \bc)\\
  &~~~ - \int_{m} E[Y | A = \uwave{a_{0}}, M = m, \bC = \bc] \mathrm{d}F(M = m | A = a_{0}, \bC = \bc)\\
  &= \int_{m} E[Y | A = \uwave{a_{0}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ \mathrm{d}F(M = m | A = a_{1}, \bC = \bc) - \mathrm{d}F(M = m | A = a_{0}, \bC = \bc) \right\}\\
  &= \left\{
  \begin{aligned}
  &~~~\text{For continuous }M\\
  &\int_{m} E[Y | A = \uwave{a_{0}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ \mathrm{d}F(M = m | A = a_{1}, \bC = \bc) - \mathrm{d}F(M = m | A = a_{0}, \bC = \bc) \right\}\\
  &\\
  &~~~\text{For discrete }M\\
  &\sum_{m} E[Y | A = \uwave{a_{0}}, M = m, \bC = \bc]\\
  &~~~ \times \left\{ \mathrm{d}F(M = m | A = a_{1}, \bC = \bc) - \mathrm{d}F(M = m | A = a_{0}, \bC = \bc) \right\}\\
  \end{aligned}
\right .\\
\end{align*}


* Implementation of the regression-based causal mediation analysis method
Here we describe the formulas implemented in =regmedint=, using the notational convention in cite:vanderweeleExplanationCausalInference2015,valeriMediationAnalysisAllowing2013,valeriSASMacroCausal2015. In addition to what can be found in the appendix of cite:vanderweeleExplanationCausalInference2015, we provide the explicit expressions for the alternative TNDE-PNIE decomposition. The differences are highlighted with $\uwave{~~~~}$.

** Parametrizing the mediation effect formulas
A seen above, there are two models involved in identification of natural effects: the outcome model ($E[Y|A=a,M=m,\bC=\bc]$) and the mediator model ($p(M|A=a,\bC=\bc)$). The identification formulas do not specify any particular model structure (non-parametric). In the method described in cite:valeriMediationAnalysisAllowing2013,valeriSASMacroCausal2015, a simple parametric model is proposed for each.\\

The mediator model with a link function $g_{M}$ is parametrized as follows.
\begin{align*}
  g_{M}(E[M|A=a,\bC=\bc]) &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc
\end{align*}

The outcome model with a link function $g_{Y}$ is parametrized as follows.
\begin{align*}
  g_{Y}(E[Y|A=a,M=m,\bC=\bc]) &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc
\end{align*}

Under these parametric modeling assumptions, each effect of interest can be written as a function of the parameters (coefficients) of the the mediator model ($\beta$ and sometimes $\sigma^{2}$) and the outcome model ($\theta$). Because of the product configuration (outcome model \times mediator model), each natural effect is a non-linear function of the parameters (model coefficients). The maximum likelihood estimates (MLE) of these effects are the ones with these parameters replaced with their respective MLEs from the two models.

** Obtaining standard errors via multivariate delta method

Each effect of interest is estimated as a scalar-valued, non-linear function of estiamted coefficients for the mediator model and the outcome model. Thus, we can obtain the standard error of each effect estimate using the variance covariance matrix for the coefficients and multivariate delta method cite:hoefWhoInventedDelta2012.\\

Let the scalar quantity of interest be $Q$, a function of parameter vector $(\bbeta^{T},\btheta^{T})^{T}$. Then, its gradient (vector of partial derivatives) with respect to the parameter vector $(\bbeta^{T},\btheta^{T})^{T}$ is the following.\\

\begin{align*}
\nabla Q &= \frac{\partial Q}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
         &= \begin{bmatrix}
           \frac{\partial Q}{\partial \beta_{0}}\\[6pt]
           \frac{\partial Q}{\partial \beta_{1}}\\[6pt]
           \frac{\partial Q}{\partial \bbeta_{2}}\\[6pt]
           \frac{\partial Q}{\partial \theta_{0}}\\[6pt]
           \frac{\partial Q}{\partial \theta_{1}}\\[6pt]
           \frac{\partial Q}{\partial \theta_{2}}\\[6pt]
           \frac{\partial Q}{\partial \theta_{3}}\\[6pt]
           \frac{\partial Q}{\partial \btheta_{4}}\\
         \end{bmatrix}\\
\end{align*}

In the case of a linear mediator model and a non-linear outcome model, there is an additional element $\frac{\partial Q}{\partial \sigma^{2}}$ at the bottom of the gradient vector.\\

By the large sample approximation using the multivariate delta method, the variance of the quantity of interest evaluated at the MLEs $(\bbetahat^{T},\bthetahat^{T})^{T}$ is the following.

\begin{align*}
  \underbrace{Var \left[ Q\left\{ (\bbetahat^{T},\bthetahat^{T})^{T} \right\} \right]}_{\text{scalar}}
  &\approx
  \underbrace{\left[ \nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right) \right]^{T}}_{\text{row vector}}
  \underbrace{Var((\bbetahat^{T},\bthetahat^{T})^{T})}_{\text{matrix}}
  \underbrace{\left[ \nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right) \right]}_{\text{column vector}}
\end{align*}

This expression is abbreviated as $\Gamma\Sigma\Gamma'$ in cite:vanderweeleExplanationCausalInference2015,valeriMediationAnalysisAllowing2013,valeriSASMacroCausal2015. In these references, the treatment contrast ($a_{1}-a_{0}$) is factored out from $\nabla Q \left( (\bbetahat^{T},\bthetahat^{T})^{T} \right)$ when possible. In the following, we define $\Gamma$ as a column vector to be consistent with the implementation of =regmedint=, thus, the corresponding expression appears as $\Gamma^{T}\Sigma\Gamma$.

** Linear mediator model, linear outcome model
*** Effect formulas
The function =calc_myreg_mreg_linear_yreg_linear_est()= implements the effect formulas in cite:vanderweeleExplanationCausalInference2015 (p466).

\begin{align*}
  &\text{Models}\\
  E[Y|A=a,M=m,\bC=\bc] &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc\\
  E[M|A=a,\bC=\bc] &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc\\
  \\
  &\text{Effects}\\
  CDE(m) &= E[Y_{a_{1},m} | \bC = \bc] - E[Y_{a_{0},m} | \bC = \bc]\\
  &= (\theta_{1} + \theta_{3}m)(a_{1} - a_{0})\\
  \\
  PNDE &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc) \right\} (a_{1} - a_{0})\\
  TNIE &= E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc]\\
  &= \beta_{1}(\theta_{2} + \theta_{3}\uwave{a_{1}})(a_{1} - a_{0})\\
  \\
  TNDE &= E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc) \right\} (a_{1} - a_{0})\\
  PNIE &= E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc]\\
  &= \beta_{1}(\theta_{2} + \theta_{3}\uwave{a_{0}})(a_{1} - a_{0})\\
  \\
  TE &= PNDE + TNIE\\
  PM &= \frac{TNIE}{PNDE + TNIE}\\
\end{align*}

*** Variance formulas
The function =calc_myreg_mreg_linear_yreg_linear_se()= implements the standard error formulas in cite:vanderweeleExplanationCausalInference2015 (p466).

\begin{align*}
  (a_{1}-a_{0})\Gamma_{CDE(m)}
  &= \frac{\partial CDE(m)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      0\\
      \b0\\
      0\\
      1\\
      0\\
      m\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{PNDE}
  &= \frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}\uwave{a_{0}}\\
      \theta_{3}\bc\\
      0\\
      1\\
      0\\
      \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc\\
      \b0\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{TNIE}
  &= \frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}\uwave{a_{1}}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}\uwave{a_{1}}\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TNDE}
  &= \frac{\partial TNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}\uwave{a_{1}}\\
      \theta_{3}\bc\\
      0\\
      1\\
      0\\
      \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc\\
      \b0\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{PNIE}
  &= \frac{\partial PNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}\uwave{a_{0}}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}\uwave{a_{0}}\\
      \b0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TE}
  &= \frac{\partial TE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial (PNDE+TNIE)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})(\Gamma_{PNDE} + \Gamma_{TNIE})\\
  \\
  (a_{1}-a_{0})\Gamma_{PM}
  &= \frac{\partial PM}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &~~~\text{By multivariate chain rule}\\
  &= \frac{\partial PM}{\partial PNDE}\frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}} + \frac{\partial PM}{\partial TNIE}\frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial PM}{\partial PNDE}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{\partial PM}{\partial TNIE}(a_{1}-a_{0})\Gamma_{TNIE}\\
  &= \frac{-TNIE}{(PNDE+TNIE)^{2}}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{PNDE}{(PNDE+TNIE)^{2}}(a_{1}-a_{0})\Gamma_{TNIE}\\
  &= (a_{1}-a_{0}) \frac{-TNIE~\Gamma_{PNDE} + PNDE~\Gamma_{TNIE}}{(PNDE+TNIE)^{2}}\\
  \\
  &\text{Variance-covariance matrix from two models}\\
  \bSigma &=
           \begin{bmatrix}
             \bSigma_{\bbeta} & 0 \\
             0 & \bSigma_{\btheta} \\
           \end{bmatrix}\\
  SE(\widehat{CDE}(m)) &= \sqrt{\Gamma_{CDE(m)}^{T} ~\bSigma~ \Gamma_{CDE(m)}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNDE}) &= \sqrt{\Gamma_{PNDE}^{T} ~\bSigma~ \Gamma_{PNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TNIE}) &= \sqrt{\Gamma_{TNIE}^{T} ~\bSigma~ \Gamma_{TNIE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TNDE}) &= \sqrt{\Gamma_{TNDE}^{T} ~\bSigma~ \Gamma_{TNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNIE}) &= \sqrt{\Gamma_{PNIE}^{T} ~\bSigma~ \Gamma_{PNIE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TE}) &= \sqrt{\Gamma_{TE}^{T} ~\bSigma~ \Gamma_{TE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PM}) &= \sqrt{\Gamma_{PM}^{T} ~\bSigma~ \Gamma_{PM}} ~ \abs{a_{1} - a_{0}}\\
\end{align*}


** Linear mediator model, non-linear outcome model
These formulas are used for all non-linear outcome models, including logistic (rare outcome assumption), log-linear, Poisson, negative binomial cite:valeriMediationAnalysisAllowing2013, accelerated failure time, and Cox (rare outcome assumption) cite:valeriSASMacroCausal2015.

*** Effect formulas
The function =calc_myreg_mreg_linear_yreg_logistic_est()= implements the effect formulas in cite:vanderweeleExplanationCausalInference2015 (p468).

\begin{align*}
  &\text{Models}\\
  \logit(E[Y|A=a,M=m,\bC=\bc]) &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc\\
  E[M|A=a,\bC=\bc] &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc\\
  \\
  &\text{Effects on outcome model link function scale}\\
  CDE(m) &= \logit(E[Y_{a_{1},m} | \bC = \bc]) - \logit(E[Y_{a_{0},m} | \bC = \bc])\\
  &= (\theta_{1} + \theta_{3}m)(a_{1} - a_{0})\\
  \\
  PNDE &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc])\\
  &\approx \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc + \theta_{2}\sigma^{2}) \right\} (a_{1} - a_{0}) + \frac{1}{2} \theta_{3}^{2}\sigma^{2}(a_{1}^{2} - a_{0}^{2})\\
  TNIE &= \logit(E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc]) - \logit(E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc])\\
  &\approx \beta_{1}(\theta_{2} + \theta_{3}\uwave{a_{1}})(a_{1} - a_{0})\\
  \\
  TNDE &= \logit(E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc])\\
  &\approx \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc + \theta_{2}\sigma^{2}) \right\} (a_{1} - a_{0}) + \frac{1}{2} \theta_{3}^{2}\sigma^{2}(a_{1}^{2} - a_{0}^{2})\\
  PNIE &= \logit(E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc]) - \logit(E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc])\\
  &\approx \beta_{1}(\theta_{2} + \theta_{3}\uwave{a_{0}})(a_{1} - a_{0})\\
  \\
  TE &= PNDE + TNIE\\
  PM &= \frac{\exp(PNDE)(\exp(TNIE) - 1)}{\exp(PNDE)\exp(TNIE) - 1}\\
\end{align*}

*** Variance formulas
The function =calc_myreg_mreg_linear_yreg_logistic_se()= implements the standard error formulas in cite:vanderweeleExplanationCausalInference2015 (p468).

\begin{align*}
  (a_{1}-a_{0})\Gamma_{CDE(m)}
  &= \frac{\partial CDE(m)}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      0\\
      \b0\\
      0\\
      1\\
      0\\
      m\\
      \b0\\
      0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{PNDE}
  &= \frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}\uwave{a_{0}}\\
      \theta_{3}\bc\\
      0\\
      1\\
      \theta_{3}\sigma^{2}\\
      \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc + \theta_{2}\sigma^{2} + \theta_{3}\sigma^{2}(a_{0} + a_{1})\\
      \b0\\
      \theta_{3}\theta_{2} + \frac{1}{2}\theta_{3}^{2}(a_{1} + a_{0})\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{TNIE}
  &= \frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}\uwave{a_{1}}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}\uwave{a_{1}}\\
      \b0\\
      0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TNDE}
  &= \frac{\partial TNDE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      \theta_{3}\\
      \theta_{3}\uwave{a_{1}}\\
      \theta_{3}\bc\\
      0\\
      1\\
      \theta_{3}\sigma^{2}\\
      \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc + \theta_{2}\sigma^{2} + \theta_{3}\sigma^{2}(a_{0} + a_{1})\\
      \b0\\
      \theta_{3}\theta_{2} + \frac{1}{2}\theta_{3}^{2}(a_{1} + a_{0})\\
    \end{bmatrix}\\
  (a_{1}-a_{0})\Gamma_{PNIE}
  &= \frac{\partial PNIE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      \theta_{2} + \theta_{3}\uwave{a_{0}}\\
      \b0\\
      0\\
      0\\
      \beta_{1}\\
      \beta_{1}\uwave{a_{0}}\\
      \b0\\
      0\\
    \end{bmatrix}\\
  \\
  (a_{1}-a_{0})\Gamma_{TE}
  &= \frac{\partial TE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= \frac{\partial (PNDE+TNIE)}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= (a_{1}-a_{0})(\Gamma_{PNDE} + \Gamma_{TNIE})\\
  \\
  (a_{1}-a_{0})\Gamma_{PM}
  &= \frac{\partial PM}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &~~~\text{By multivariate chain rule}\\
  &= \frac{\partial PM}{\partial PNDE}\frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}} + \frac{\partial PM}{\partial TNIE}\frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T},\sigma^2)^{T}}\\
  &= \frac{\partial PM}{\partial PNDE}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{\partial PM}{\partial TNIE}(a_{1}-a_{0})\Gamma_{TNIE}\\
  &= - \frac{\exp(PNDE)\left\{ \exp(TNIE) - 1 \right\}}{\left\{ \exp(PNDE)\exp(TNIE) - 1 \right\}^{2}} (a_{1}-a_{0})\Gamma_{PNDE}\\
  &~~~ + \frac{\exp(PNDE)\exp(TNIE)\left\{ \exp(PNDE) - 1 \right\}}{\left\{ \exp(PNDE)\exp(TNIE) - 1 \right\}^{2}} (a_{1}-a_{0})\Gamma_{TNIE}\\
  \\
  &\text{Variance-covariance matrix from two models}\\
  \bSigma &=
           \begin{bmatrix}
             \bSigma_{\bbeta} & 0 & 0\\
             0 & \bSigma_{\btheta} & 0\\
             0 & 0 & \Sigma_{\sigma^{2}}\\
           \end{bmatrix}\\
  \Sigma_{\sigma^{2}} &= \frac{2 (\sigma^{2})^{2}}{n - p} ~ \text{where} ~ p = \text{length}(\bbeta)\\
  SE(\widehat{CDE}(m)) &= \sqrt{\Gamma_{CDE(m)}^{T} ~\bSigma~ \Gamma_{CDE(m)}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNDE}) &= \sqrt{\Gamma_{PNDE}^{T} ~\bSigma~ \Gamma_{PNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TNIE}) &= \sqrt{\Gamma_{TNIE}^{T} ~\bSigma~ \Gamma_{TNIE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TNDE}) &= \sqrt{\Gamma_{TNDE}^{T} ~\bSigma~ \Gamma_{TNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNIE}) &= \sqrt{\Gamma_{PNIE}^{T} ~\bSigma~ \Gamma_{PNIE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TE}) &= \sqrt{\Gamma_{TE}^{T} ~\bSigma~ \Gamma_{TE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PM}) &= \sqrt{\Gamma_{PM}^{T} ~\bSigma~ \Gamma_{PM}} ~ \abs{a_{1} - a_{0}}\\
\end{align*}


** Logistic mediator model, linear outcome model
*** Effect formulas
The function =calc_myreg_mreg_logistic_yreg_linear_est()= implements the effect formulas in cite:vanderweeleExplanationCausalInference2015 (p471).

\begin{align*}
  &\text{Models}\\
  E[Y|A=a,M=m,\bC=\bc] &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc\\
  \logit(E[M|A=a,\bC=\bc]) &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc\\
  \\
  &\text{Effects}\\
  CDE(m) &= E[Y_{a_{1},m} | \bC = \bc] - E[Y_{a_{0},m} | \bC = \bc]\\
  &= (\theta_{1} + \theta_{3}m)(a_{1} - a_{0})\\
  \\
  PNDE &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  &= \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}\\
  TNIE &= E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc]\\
  &= (\theta_{2} + \theta_{3}\uwave{a_{1}})\left\{
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    -
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    \right\}
  \\
  TNDE &= E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc]\\
  &= \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}\\
  PNIE &= E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc]\\
  &= (\theta_{2} + \theta_{3}\uwave{a_{0}})\left\{
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    -
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    \right\}
  \\
  TE &= PNDE + TNIE\\
  PM &= \frac{TNIE}{PNDE + TNIE}\\
\end{align*}

*** Variance formulas
The function =calc_myreg_mreg_logistic_yreg_linear_se()= implements the standard error formulas in cite:vanderweeleExplanationCausalInference2015 (p471).

\begin{align*}
  (a_{1}-a_{0})\Gamma_{CDE(m)}
  &= \frac{\partial CDE(m)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      0\\
      0\\
      \b0\\
      0\\
      1\\
      0\\
      m\\
      \b0\\
    \end{bmatrix}\\
  \\
  d_{1,PNDE} &= \theta_{3} \frac
               {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{2,PNDE} &= \uwave{a_{0}} \theta_{3} \frac
               {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{3,PNDE} &= \bc \theta_{3} \frac
               {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{4,PNDE} &= 0\\
  d_{5,PNDE} &= 1\\
  d_{6,PNDE} &= 0\\
  d_{7,PNDE} &= \frac
               {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
               {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}\\
  d_{8,PNDE} &= \b0\\
  (a_{1}-a_{0})\Gamma_{PNDE}
  &= \frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      d_{1,PNDE}\\
      d_{2,PNDE}\\
      d_{3,PNDE}\\
      d_{4,PNDE}\\
      d_{5,PNDE}\\
      d_{6,PNDE}\\
      d_{7,PNDE}\\
      d_{8,PNDE}\\
    \end{bmatrix}\\
  \\
  Q_{TNIE} &= \frac
      {            \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {\left\{ 1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc) \right\}^{2}}\\
  B_{TNIE} &= \frac
      {            \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {\left\{ 1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc) \right\}^{2}}\\
  K_{TNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  D_{TNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  d_{1,TNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{1}}) (Q_{TNIE} - B_{TNIE})\\
  d_{2,TNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{1}}) (a_{1}Q_{TNIE} - a_{0}B_{TNIE})\\
  d_{3,TNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{1}})\bc (Q_{TNIE} - B_{TNIE})\\
  d_{4,TNIE} &= 0\\
  d_{5,TNIE} &= 0\\
  d_{6,TNIE} &= K_{TNIE} - D_{TNIE}\\
  d_{7,TNIE} &= \uwave{a_{1}} (K_{TNIE} - D_{TNIE})\\
  d_{8,TNIE} &= \b0\\
  &\text{Note the lack of the common factor }(a_{1} - a_{0})\\
  \Gamma_{TNIE}
  &= \frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,TNIE}\\
      d_{2,TNIE}\\
      d_{3,TNIE}\\
      d_{4,TNIE}\\
      d_{5,TNIE}\\
      d_{6,TNIE}\\
      d_{7,TNIE}\\
      d_{8,TNIE}\\
    \end{bmatrix}\\
  \\
  d_{1,TNDE} &= \theta_{3} \frac
               {    \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{2,TNDE} &= \uwave{a_{1}} \theta_{3} \frac
               {    \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{3,TNDE} &= \bc \theta_{3} \frac
               {    \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
               {\{1 + \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)\}^{2}}\\
  d_{4,TNDE} &= 0\\
  d_{5,TNDE} &= 1\\
  d_{6,TNDE} &= 0\\
  d_{7,TNDE} &= \frac
               {    \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
               {1 + \exp(\beta_{1} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}\\
  d_{8,TNDE} &= \b0\\
  (a_{1}-a_{0})\Gamma_{TNDE}
  &= \frac{\partial TNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})
    \begin{bmatrix}
      d_{1,TNDE}\\
      d_{2,TNDE}\\
      d_{3,TNDE}\\
      d_{4,TNDE}\\
      d_{5,TNDE}\\
      d_{6,TNDE}\\
      d_{7,TNDE}\\
      d_{8,TNDE}\\
    \end{bmatrix}\\
  \\
  Q_{PNIE} &= \frac
      {            \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {\left\{ 1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc) \right\}^{2}}\\
  B_{PNIE} &= \frac
      {            \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {\left\{ 1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc) \right\}^{2}}\\
  K_{PNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  D_{PNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  d_{1,PNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{0}}) (Q_{PNIE} - B_{PNIE})\\
  d_{2,PNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{0}}) (a_{1}Q_{PNIE} - a_{0}B_{PNIE})\\
  d_{3,PNIE} &= (\theta_{2} + \theta_{3}\uwave{a_{0}})\bc (Q_{PNIE} - B_{PNIE})\\
  d_{4,PNIE} &= 0\\
  d_{5,PNIE} &= 0\\
  d_{6,PNIE} &= K_{PNIE} - D_{PNIE}\\
  d_{7,PNIE} &= \uwave{a_{0}} (K_{PNIE} - D_{PNIE})\\
  d_{8,PNIE} &= \b0\\
  &\text{Note the lack of the common factor }(a_{1} - a_{0})\\
  \Gamma_{PNIE}
  &= \frac{\partial PNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,PNIE}\\
      d_{2,PNIE}\\
      d_{3,PNIE}\\
      d_{4,PNIE}\\
      d_{5,PNIE}\\
      d_{6,PNIE}\\
      d_{7,PNIE}\\
      d_{8,PNIE}\\
    \end{bmatrix}\\
  \\
  &\text{Note the lack of the common factor }(a_{1} - a_{0})\\
  \Gamma_{TE}
  &= \frac{\partial TE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial (PNDE+TNIE)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= (a_{1}-a_{0})\Gamma_{PNDE} + \Gamma_{TNIE}\\
  \\
  &\text{Note the lack of the common factor }(a_{1} - a_{0})\\
  \Gamma_{PM}
  &= \frac{\partial PM}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &~~~\text{By multivariate chain rule}\\
  &= \frac{\partial PM}{\partial PNDE}\frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}} + \frac{\partial PM}{\partial TNIE}\frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial PM}{\partial PNDE}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{\partial PM}{\partial TNIE}\Gamma_{TNIE}\\
  &= \frac{-TNIE}{(PNDE+TNIE)^{2}}(a_{1}-a_{0})\Gamma_{PNDE} + \frac{PNDE}{(PNDE+TNIE)^{2}}\Gamma_{TNIE}\\
  &= \frac{-TNIE~(a_{1}-a_{0})\Gamma_{PNDE} + PNDE~\Gamma_{TNIE}}{(PNDE+TNIE)^{2}}\\
  \\
  &\text{Variance-covariance matrix from two models}\\
  \bSigma &=
           \begin{bmatrix}
             \bSigma_{\bbeta} & 0 \\
             0 & \bSigma_{\btheta} \\
           \end{bmatrix}\\
  SE(\widehat{CDE}(m)) &= \sqrt{\Gamma_{CDE(m)}^{T} ~\bSigma~ \Gamma_{CDE(m)}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNDE}) &= \sqrt{\Gamma_{PNDE}^{T} ~\bSigma~ \Gamma_{PNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{TNIE}) &= \sqrt{\Gamma_{TNIE}^{T} ~\bSigma~ \Gamma_{TNIE}}\\
  SE(\widehat{TNDE}) &= \sqrt{\Gamma_{TNDE}^{T} ~\bSigma~ \Gamma_{TNDE}} ~ \abs{a_{1} - a_{0}}\\
  SE(\widehat{PNIE}) &= \sqrt{\Gamma_{PNIE}^{T} ~\bSigma~ \Gamma_{PNIE}}\\
  SE(\widehat{TE}) &= \sqrt{\Gamma_{TE}^{T} ~\bSigma~ \Gamma_{TE}}\\
  SE(\widehat{PM}) &= \sqrt{\Gamma_{PM}^{T} ~\bSigma~ \Gamma_{PM}}\\
\end{align*}


** Logistic mediator model, non-linear outcome model
These formulas are used for all non-linear outcome models, including logistic (rare outcome assumption), log-linear, Poisson, negative binomial cite:valeriMediationAnalysisAllowing2013, accelerated failure time, and Cox (rare outcome assumption) cite:valeriSASMacroCausal2015.

*** Effect formulas
The function =calc_myreg_mreg_logistic_yreg_logistic_est()= implements the effect formulas in cite:vanderweeleExplanationCausalInference2015 (p473).

\begin{align*}
  &\text{Models}\\
  \logit(E[Y|A=a,M=m,\bC=\bc]) &= \theta_{0} + \theta_{1}a + \theta_{2}m + \theta_{3}am + \btheta_{4}^{T}\bc\\
  \logit(E[M|A=a,\bC=\bc]) &= \beta_{0} + \beta_{1}a + \bbeta_{2}^{T}\bc
\end{align*}
# Separate to avoid an excessive right shift of the following.
\begin{align*}
  &\text{Effects on outcome model link function scale}\\
  CDE(m) &= \logit(E[Y_{a_{1},m} | \bC = \bc]) - \logit(E[Y_{a_{0},m} | \bC = \bc])\\
  &= (\theta_{1} + \theta_{3}m)(a_{1} - a_{0})\\
  \\
  PNDE &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc])\\
  &\approx \theta_{1}(a_{1} - a_{0})\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bc))\\
  TNIE &= \logit(E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc]) - \logit(E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc])\\
  &\approx \log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  \\
  &\text{Note the $a_{0} \rightarrow a_{1}$ changes associated with $\beta_{1}$.}\\
  TNDE &= \logit(E[Y_{a_{1},\uwave{M_{a_{1}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{1}}}} | \bC = \bc])\\
  &\approx \theta_{1}(a_{1} - a_{0})\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{1}} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{1}} + \bbeta_{2}^T\bc))\\
  &\text{Note the $a_{1} \rightarrow a_{0}$ changes associated with $\theta_{3}$.}\\
  PNIE &= \logit(E[Y_{\uwave{a_{0}},M_{a_{1}}} | \bC = \bc]) - \logit(E[Y_{\uwave{a_{0}},M_{a_{0}}} | \bC = \bc])\\
  &\approx \log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  \\
  TE &= PNDE + TNIE\\
  PM &= \frac{\exp(PNDE)(\exp(TNIE) - 1)}{\exp(PNDE)\exp(TNIE) - 1}\\
\end{align*}

*** Variance formulas
The function =calc_myreg_mreg_logistic_yreg_logistic_se()= implements the standard error formulas in cite:vanderweeleExplanationCausalInference2015 (p473).

\begin{align*}
  &\text{Note the lack of the common factor $(a_{1} - a_{0})$ throughout.}\\
  \Gamma_{CDE(m)}
  &= \frac{\partial CDE(m)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &=
    \begin{bmatrix}
      0\\
      0\\
      \b0\\
      0\\
      (a_{1} - a_{0})\\
      0\\
      m(a_{1} - a_{0})\\
      \b0\\
    \end{bmatrix}\\
  \\
  Q_{PNDE} &= \frac
             {    \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
             {1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}\\
  B_{PNDE} &= \frac
             {    \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
             {1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}\\
      d_{1,PNDE} &= Q_{PNDE} - B_{PNDE}\\
      d_{2,PNDE} &= \uwave{a_{0}} (Q_{PNDE} - B_{PNDE})\\
      d_{3,PNDE} &= \bc (Q_{PNDE} - B_{PNDE})\\
      d_{4,PNDE} &= 0\\
      d_{5,PNDE} &= a_{1} - a_{0}\\
      d_{6,PNDE} &= Q_{PNDE} - B_{PNDE}\\
      d_{7,PNDE} &= a_{1}Q_{PNDE} - a_{0}B_{PNDE}\\
      d_{8,PNDE} &= \b0\\
  \Gamma_{PNDE}
  &= \frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,PNDE}\\
      d_{2,PNDE}\\
      d_{3,PNDE}\\
      d_{4,PNDE}\\
      d_{5,PNDE}\\
      d_{6,PNDE}\\
      d_{7,PNDE}\\
      d_{8,PNDE}\\
    \end{bmatrix}\\
  \\
  Q_{TNIE} &= \frac
      {    \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  B_{TNIE} &= \frac
      {    \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  K_{TNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  D_{TNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  d_{1,TNIE} &= (D_{TNIE} + Q_{TNIE}) - (K_{TNIE} + B_{TNIE})\\
  d_{2,TNIE} &= a_{0}(D_{TNIE} - B_{TNIE}) + a_{1}(Q_{TNIE} - K_{TNIE})\\
  d_{3,TNIE} &= \bc \left\{ (D_{TNIE} + Q_{TNIE}) - (K_{TNIE} + B_{TNIE}) \right\}\\
  d_{4,TNIE} &= 0\\
  d_{5,TNIE} &= 0\\
  d_{6,TNIE} &= Q_{TNIE} - B_{TNIE}\\
  d_{7,TNIE} &= \uwave{a_{1}} (Q_{TNIE} - B_{TNIE})\\
  d_{8,TNIE} &= \b0\\
  \Gamma_{TNIE}
  &= \frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,TNIE}\\
      d_{2,TNIE}\\
      d_{3,TNIE}\\
      d_{4,TNIE}\\
      d_{5,TNIE}\\
      d_{6,TNIE}\\
      d_{7,TNIE}\\
      d_{8,TNIE}\\
    \end{bmatrix}\\
  \\
  Q_{TNDE} &= \frac
             {    \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
             {1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}\\
  B_{TNDE} &= \frac
             {    \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}
             {1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1}\uwave{a_{1}} + \bbeta_{2}^{T}\bc)}\\
      d_{1,TNDE} &= Q_{TNDE} - B_{TNDE}\\
      d_{2,TNDE} &= \uwave{a_{1}} (Q_{TNDE} - B_{TNDE})\\
      d_{3,TNDE} &= \bc (Q_{TNDE} - B_{TNDE})\\
      d_{4,TNDE} &= 0\\
      d_{5,TNDE} &= a_{1} - a_{0}\\
      d_{6,TNDE} &= Q_{TNDE} - B_{TNDE}\\
      d_{7,TNDE} &= a_{1}Q_{TNDE} - a_{0}B_{TNDE}\\
      d_{8,TNDE} &= \b0\\
  \Gamma_{TNDE}
  &= \frac{\partial TNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,TNDE}\\
      d_{2,TNDE}\\
      d_{3,TNDE}\\
      d_{4,TNDE}\\
      d_{5,TNDE}\\
      d_{6,TNDE}\\
      d_{7,TNDE}\\
      d_{8,TNDE}\\
    \end{bmatrix}\\
  \\
  Q_{PNIE} &= \frac
      {    \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  B_{PNIE} &= \frac
      {    \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{0}} + \beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  K_{PNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}\\
  D_{PNIE} &= \frac
      {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
      {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}\\
  d_{1,PNIE} &= (D_{PNIE} + Q_{PNIE}) - (K_{PNIE} + B_{PNIE})\\
  d_{2,PNIE} &= a_{0}(D_{PNIE} - B_{PNIE}) + a_{1}(Q_{PNIE} - K_{PNIE})\\
  d_{3,PNIE} &= \bc \left\{ (D_{PNIE} + Q_{PNIE}) - (K_{PNIE} + B_{PNIE}) \right\}\\
  d_{4,PNIE} &= 0\\
  d_{5,PNIE} &= 0\\
  d_{6,PNIE} &= Q_{PNIE} - B_{PNIE}\\
  d_{7,PNIE} &= \uwave{a_{0}} (Q_{PNIE} - B_{PNIE})\\
  d_{8,PNIE} &= \b0\\
  \Gamma_{PNIE}
  &= \frac{\partial PNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \begin{bmatrix}
      d_{1,PNIE}\\
      d_{2,PNIE}\\
      d_{3,PNIE}\\
      d_{4,PNIE}\\
      d_{5,PNIE}\\
      d_{6,PNIE}\\
      d_{7,PNIE}\\
      d_{8,PNIE}\\
    \end{bmatrix}\\
  \\
  \Gamma_{TE}
  &= \frac{\partial TE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial (PNDE+TNIE)}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \Gamma_{PNDE} + \Gamma_{TNIE}\\
  \\
  \Gamma_{PM}
  &= \frac{\partial PM}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &~~~\text{By multivariate chain rule}\\
  &= \frac{\partial PM}{\partial PNDE}\frac{\partial PNDE}{\partial (\bbeta^{T},\btheta^{T})^{T}} + \frac{\partial PM}{\partial TNIE}\frac{\partial TNIE}{\partial (\bbeta^{T},\btheta^{T})^{T}}\\
  &= \frac{\partial PM}{\partial PNDE}\Gamma_{PNDE} + \frac{\partial PM}{\partial TNIE}\Gamma_{TNIE}\\
  &= - \frac{\exp(PNDE)\left\{ \exp(TNIE) - 1 \right\}}{\left\{ \exp(PNDE)\exp(TNIE) - 1 \right\}^{2}} \Gamma_{PNDE}\\
  &~~~ + \frac{\exp(PNDE)\exp(TNIE)\left\{ \exp(PNDE) - 1 \right\}}{\left\{ \exp(PNDE)\exp(TNIE) - 1 \right\}^{2}} \Gamma_{TNIE}\\
  \\
  &\text{Variance-covariance matrix from two models}\\
  \bSigma &=
           \begin{bmatrix}
             \bSigma_{\bbeta} & 0 \\
             0 & \bSigma_{\btheta} \\
           \end{bmatrix}\\
  SE(\widehat{CDE}(m)) &= \sqrt{\Gamma_{CDE(m)}^{T} ~\bSigma~ \Gamma_{CDE(m)}}\\
  SE(\widehat{PNDE}) &= \sqrt{\Gamma_{PNDE}^{T} ~\bSigma~ \Gamma_{PNDE}}\\
  SE(\widehat{TNIE}) &= \sqrt{\Gamma_{TNIE}^{T} ~\bSigma~ \Gamma_{TNIE}}\\
  SE(\widehat{TNDE}) &= \sqrt{\Gamma_{TNDE}^{T} ~\bSigma~ \Gamma_{TNDE}}\\
  SE(\widehat{PNIE}) &= \sqrt{\Gamma_{PNIE}^{T} ~\bSigma~ \Gamma_{PNIE}}\\
  SE(\widehat{TE}) &= \sqrt{\Gamma_{TE}^{T} ~\bSigma~ \Gamma_{TE}}\\
  SE(\widehat{PM}) &= \sqrt{\Gamma_{PM}^{T} ~\bSigma~ \Gamma_{PM}}\\
\end{align*}


* Software user guide and reproducible code
** Pointers to =regmedint= online user guide
Further details of the software =regmedint= are given on its website (https://kaz-yos.github.io/regmedint/index.html). In particular, the online vignettes for the package should be useful.

1. [[https://kaz-yos.github.io/regmedint/articles/vig_01_introduction.html][*Introduction to user interface functions*]]
   - URL: https://kaz-yos.github.io/regmedint/articles/vig_01_introduction.html
   - Explains all user interface functions and their outputs.
2. [[https://kaz-yos.github.io/regmedint/articles/vig_02_formulas.html][*Implementation of formulas*]]
   - URL: https://kaz-yos.github.io/regmedint/articles/vig_02_formulas.html
   - Demonstrates internal functions implementing formulas.
3. [[https://kaz-yos.github.io/regmedint/articles/vig_03_bootstrap.html][*Using bootstrapping with regemedint*]]
   - URL: https://kaz-yos.github.io/regmedint/articles/vig_03_bootstrap.html
   - Implements bootstrap confidence intervals with the =boot= and =modelr= packages.
4. [[https://kaz-yos.github.io/regmedint/articles/vig_04_mi.html][*Using multiple imputation with regmedint*]]
   - URL: https://kaz-yos.github.io/regmedint/articles/vig_04_mi.html
   - Shows how to use multiple imputation via the =mice= and =mitools= packages.

In the following, we included the minimum code to reproduce the example causal mediation analysis in the paper.

** Generating the example data
The demonstration data used in the paper was generated as follows in =R= version 4.0.0 on macOS version 10.15.5.

\begin{align*}
  n
  &= 1000\\
  \\
  &\text{Covariates}\\
  C_{1,i} &\overset{\text{iid}}{\sim} N(0,1)\\
  C_{2,i} &\overset{\text{iid}}{\sim} N(0,1)\\
  \\
  &\text{Binary treatment}\\
  \logit(E[A_{i} | C_{1,i}, C_{2,i}])
  &= -0.5 + 0.1 C_{1,i} + 0.2 C_{2,i}\\
  A_{i} &\sim Bernoulli(p = E[A_{i} | C_{1,i}, C_{2,i}])\\
  \\
  &\text{Continuous mediator}\\
  E[M_{i} | A_{i}, C_{1,i}, C_{2,i}]
  &= 0 + 0.5 A_{i} - 0.1 C_{1,i} + 0.3 C_{2,i}\\
  M_{i} &\sim N(E[M_{i} | A_{i}, C_{1,i}, C_{2,i}], 0.5^{2})\\
  \\
  &\text{Exponential event time}\\
  \lambda_{T_{i}} &= 0 + 0.3 A_{i} + 0.15 M_{i} + 0.05 A_{i}M_{i} -0.2 C_{1,i} - 0.4 C_{2,i}\\
  T_{i} &\sim Exponential(\lambda_{T_{i}})\\
  \\
  &\text{Exponential censoring time}\\
  C_{i} &\sim Exponential(\exp(-0.5))\\
  \\
  &\text{Observed time and event}\\
  \text{time}_{i} &= \min(T_{i}, C_{i}, 10)\\
  \text{event}_{i} &= I(T_{i} < C_{i}) I(T_{i} < 10)\\
\end{align*}

\scriptsize
#+BEGIN_SRC R :session *R-org* :results output :exports both
suppressMessages(library(tidyverse))
library(survival)
library(tableone)
set.seed(248361264)
## Sample size
n <- 1000
## Demo data
demo <-
  ## Covariates
  tibble(id = seq_len(n),
         c1 = rnorm(n = n, mean = 0, sd = 1),
         c2 = rnorm(n = n, mean = 0, sd = 1)) %>%
  ## Binary treatment
  mutate(logit_p_a = (-0.5) + (0.1 * c1) + (0.2 * c2),
         p_a = exp(logit_p_a) / (1 + exp(logit_p_a)),
         a = rbinom(n = n, size = 1, prob = p_a)) %>%
  ## Continuous mediator
  mutate(lp_m = 0 + (0.5 * a) + (-0.1 * c1) + (0.3 * c2),
         m = rnorm(n = n, mean = lp_m, sd = 0.5)) %>%
  ## Exponential event time
  mutate(lp_t = 0 + (0.3 * a) + (0.15 * m) + (0.05 * a * m) + (-0.2 * c1) + (-0.4 * c2),
         ## The "mean" argument is on the linear predictor scale.
         t = rsurvreg(n = n, mean = lp_t, scale = 1, distribution = "exponential")) %>%
  ## Exponential censoring time
  mutate(log_rate_cens = -0.5,
         cens = rexp(n = n, rate = exp(log_rate_cens)),
         admin_cens = 10) %>%
  ## Observed time and event
  mutate(time = pmin(t, cens, admin_cens),
         event = as.numeric((t < cens) & (t < admin_cens))) %>%
  ## Clean
  select(id, c1, c2, a, m, time, event)
## Summarize generated data
cat("### Summary of the generated data\n")
CreateTableOne(vars = c("c1","c2","m","time","event"),
               strata = c("a"),
               data = demo,
               factorVars = c("event"),
               test = FALSE,
               addOverall = TRUE) %>%
  print()
#+END_SRC
\normalsize

** Reproducing the data analysis example
The example data analysis included in the paper was conducted as follows. Please note all variables must be numeric. Multi-category variables must be recoded as multiple dichotomous (0, 1) variables.
\scriptsize
#+BEGIN_SRC R :session *R-org* :results output :exports both
library(regmedint)
## Model fitting
res_obj <- regmedint(data = demo,
                     yvar = "time", avar = "a", mvar = "m", cvar = c("c1","c2"), eventvar = "event",
                     a0 = 0, a1 = 1, m_cde = 0, c_cond = c(0.02, -0.01),
                     mreg = "linear", yreg = "survAFT_weibull",
                     interaction = TRUE, casecontrol = FALSE)
## Result extraction
summary(res_obj, exponentiate = TRUE)
#+END_SRC
\normalsize

As seen above, the mediator regression model, the outcome regression model, and the mediation analysis results are presented. The results also include the values of =a0= (reference treatment level), =a1= (treatment level of interest), =m_cde= (value at which the mediator is fixed; relevant for =cde= only), and =c_cond= (covariate vector value; relevant for natural direct and indirect effects only) at which the effect estimates are evaluated.\\

The =summary= function has the corresponding arguments =a0=, =a0=, =m_cde=, and =c_cond= to override these without unnecessarily refitting the models. Here the =m_cde= value is overriden (=coef= is used to avoid printing the same mediator and outcome model results).

\scriptsize
#+BEGIN_SRC R :session *R-org* :results output :exports both
## Re-evaluate cde at m_cde = 0.5
coef(summary(res_obj, exponentiate = TRUE, m_cde = 0.5))
#+END_SRC
\normalsize

The following code was used to create the table included in the paper.

# https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-R.html
\scriptsize
#+BEGIN_SRC R :session *R-org* :results output latex :exports both
cols <- c("est","lower","upper","exp(est)","exp(lower)","exp(upper)")
rows <- c("te","pnde","tnie","pm")
## Construct a production-level table
tab <- rbind(coef(summary(res_obj, exponentiate = TRUE))[rows,cols],
            coef(summary(res_obj, exponentiate = TRUE, m_cde = 0.0))["cde",cols, drop = FALSE],
            coef(summary(res_obj, exponentiate = TRUE, m_cde = 0.5))["cde",cols, drop = FALSE]) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  mutate(rowname = case_when(rowname == "te" ~ "Total Effect (TE)",
                             rowname == "pnde" ~ " Pure Natural Direct Effect (PNDE)",
                             rowname == "tnie" ~ " Total Natural Indirect Effect (TNIE)",
                             rowname == "pm" ~ " Proportion Mediated (PM)",
                             rowname == "cde" ~ " CDE at m = 0",
                             rowname == "cde.1" ~ " CDE at m = 0.5")) %>%
  mutate_at(.vars = vars(-starts_with("rowname")), function(vec) {
    if_else(!is.na(vec), sprintf("%.2f", vec), "")
  }) %>%
  mutate(est_ci = sprintf("%s [%s, %s]", est, lower, upper),
         exp_est_ci = sprintf("%s [%s, %s]", `exp(est)`, `exp(lower)`, `exp(upper)`)) %>%
  mutate(exp_est_ci = if_else(exp_est_ci == " [, ]", "-", exp_est_ci)) %>%
  add_row(rowname = "Controlled Direct Effect (CDE)",
          est_ci = "", exp_est_ci = "",
          .before = 5) %>%
  select(rowname, est_ci, exp_est_ci) %>%
  rename(Effect = rowname,
         `Est. [95% CI]` = est_ci,
         `Exp(Est.) [95% CI]` = exp_est_ci)
## Write to an Excel file
openxlsx::write.xlsx(x = tab,
                     file = "./supplement.xlsx")
## Print as a LaTeX table
tab %>%
  mutate(Effect = str_replace_all(Effect, "^ ", "- ")) %>%
  xtable::xtable() %>%
  print(include.rownames = FALSE)
#+END_SRC
\normalsize

All effect estimates are estimates of conditional effects, conditioning on the covariates in =c_var=. Since the outcome model is an accelerated failure time model (Weibull model), the estimates are on the log mean time ratio scale (positive values indicate beneficial effects). The exponentiated estimates are on the mean time ratio scale (values > 1.0 indicate beneficial effects). As the outcome model is a non-linear model, the proportion mediated is calculated using a transformation of the ratio scale cite:vanderweeleOddsRatiosMediation2010.

* Demonstration of covariate-dependence of natural effect estimates
We here use the =regmedint= package to describe a somewhat overlooked aspect of the regression-based estimation method, \textit{i.e.}, covariate-dependence of conditional effect estimates. Although neither the mediator model nor the outcome model has interaction terms between the treatment variable and baseline covariates, the resulting conditional effect estimates are dependent on the baseline covariate vector value at which they are evaluated (=c_cond= argument). This subtle point regarding the regression-based causal mediation method has previously been mentioned cite:steenFlexibleMediationAnalysis2017,starkopfComparisonFiveSoftware2017, but remains relatively unknown. Using simulated data, we visualy demonstrate the issue, clarify their implications on estimation of marginal effects, and then state potential approaches to reporting of the results.

** Generating demonstration data
As explained in Section [[* Implementation of the regression-based causal mediation analysis method]], there are four sets of formulas to cover linear and logistic mediator models as well as linear and non-linear outcome models. Here we generate normal (linear) and Poisson (non-linear) outcomes for demonstration. For simplicity, only one continuous covariate (=c1=) is involved in the simulated data.

\begin{align*}
  n
  &= 1000\\
  \\
  &\text{Covariates}\\
  C_{1,i} &\overset{\text{iid}}{\sim} N(0,1)\\
  \\
  &\text{Binary treatment}\\
  \logit(E[A_{i} | C_{1,i}])
  &= -0.5 + 0.1 C_{1,i}\\
  A_{i} &\sim Bernoulli(p = E[A_{i} | C_{1,i}])\\
  \\
  &\text{Mediator, continuous}\\
  E[M_{cont,i} | A_{i}, C_{1,i}, C_{2,i}]
  &= 0 + 0.5 A_{i} + 0.5 C_{1,i}\\
  M_{cont,i} &\sim N(E[M_{i} | A_{i}, C_{1,i}, C_{2,i}], 0.5^{2})\\
  &\text{Mediator, binary}\\
  E[M_{bin,i} | A_{i}, C_{1,i}, C_{2,i}]
  &= -0.9 + 0.5 A_{i} + 0.5 C_{1,i}\\
  M_{bin,i} &\sim Bernoulli(E[M_{i} | A_{i}, C_{1,i}, C_{2,i}])\\
  \\
  &\text{Outcome, continuous (continuous mediator)}\\
  E[Y_{cont,Mcont,i} | A_{i}, M_{cont,i}, C_{1,i}]
  &= 0 + 0.3 A_{i} + 0.15 M_{cont,i} + 0.05 A_{i} M_{cont,i} -0.2 C_{1,i}\\
  Y_{cont,Mcont,i} &\sim N(E[Y_{cont,Mcont,i} | A_{i}, M_{cont,i}, C_{1,i}], 1)\\
  &\text{Outcome, continuous (binary mediator)}\\
  E[Y_{cont,Mbin,i} | A_{i}, M_{bin,i}, C_{1,i}]
  &= 0 + 0.3 A_{i} + 0.15 M_{bin,i} + 0.05 A_{i} M_{bin,i} -0.2 C_{1,i}\\
  Y_{cont,Mbin,i} &\sim N(E[Y_{cont,Mbin,i} | A_{i}, M_{bin,i}, C_{1,i}], 1)\\
  \\
  &\text{Outcome, Poisson (continuous mediator)}\\
  \log(E[Y_{pois,Mcont,i} | A_{i}, M_{cont,i}, C_{1,i}])
  &= 0 + 0.3 A_{i} + 0.15 M_{cont,i} + 0.05 A_{i} M_{cont,i} -0.2 C_{1,i}\\
  Y_{pois,Mcont,i} &\sim Poisson(E[Y_{pois,Mcont,i} | A_{i}, M_{cont,i}, C_{1,i}])\\
  &\text{Outcome, Poisson (binary mediator)}\\
  \log(E[Y_{pois,Mbin,i} | A_{i}, M_{bin,i}, C_{1,i}])
  &= 0 + 0.3 A_{i} + 0.15 M_{bin,i} + 0.05 A_{i} M_{bin,i} -0.2 C_{1,i}\\
  Y_{pois,Mbin,i} &\sim Poisson(E[Y_{pois,Mbin,i} | A_{i}, M_{bin,i}, C_{1,i}])\\
\end{align*}

\scriptsize
#+BEGIN_SRC R :session *R-org* :results output :exports both
suppressMessages(library(tidyverse))
library(tableone)
set.seed(248361264)
## Sample size
n <- 1000
## Demo data
demo2 <-
  ## Covariates
  tibble(id = seq_len(n),
         c1 = rnorm(n = n, mean = 0, sd = 1)) %>%
  ## Binary treatment
  mutate(logit_p_a = (-0.5) + (0.1 * c1),
         p_a = exp(logit_p_a) / (1 + exp(logit_p_a)),
         a = rbinom(n = n, size = 1, prob = p_a)) %>%
  ## Continuous and binary mediator
  mutate(lp_m_cont = 0 + (0.5 * a) + (0.5 * c1),
         m_cont = rnorm(n = n, mean = lp_m_cont, sd = 0.5),
         lp_m_bin = -0.9 + (0.5 * a) + (0.5 * c1),
         p_m_bin = exp(lp_m_bin) / (1 + exp(lp_m_bin)),
         m_bin = rbinom(n = n, size = 1, prob = p_m_bin)) %>%
  ## Outcomes
  mutate(lp_y_m_cont = 0 + (0.3 * a) + (0.15 * m_cont) + (0.05 * a * m_cont) + (-0.2 * c1),
         lp_y_m_bin = 0 + (0.3 * a) + (0.15 * m_bin) + (0.05 * a * m_bin) + (-0.2 * c1),
         ## Normal continuous outcomes
         y_cont_m_cont = rnorm(n = n, mean = lp_y_m_cont, sd = 1),
         y_cont_m_bin = rnorm(n = n, mean = lp_y_m_bin, sd = 1),
         ## Poisson count outcomes
         y_pois_m_cont = rpois(n = n, lambda = exp(lp_y_m_cont)),
         y_pois_m_bin = rpois(n = n, lambda = exp(lp_y_m_bin)),
         ) %>%
  ## Clean
  select(id, c1, a, m_cont, m_bin,
         y_cont_m_cont, y_cont_m_bin,
         y_pois_m_cont, y_pois_m_bin)
## Summarize generated data
CreateTableOne(vars = setdiff(names(demo2), "id"),
               strata = c("a"),
               data = demo2,
               test = FALSE,
               addOverall = TRUE) %>%
  print()
#+END_SRC
\normalsize

** Demonstrating covariate dependence visually
Here we fit models 8 times to cover the four patterns stated above with or without an treatment-mediator interaction term in the outcome model. The resulting effect estimates are re-evaluated at various covariate values to reveal their relationship.
\scriptsize
#+HEADER: :width 7 :height 7
#+BEGIN_SRC R :session *R-org* :results output graphics file :file ./figure.pdf :exports both
suppressMessages(library(tidyverse))
## A grid of c_cond values to evaluate the effects at.
c_cond_grid <- seq(from = -10, to = +10, by = 0.1)
## Collect demonstration results
res <-
  ## Construct 8 patterns
  tibble(mreg = rep(c("linear","linear","logistic","logistic"), 2),
         yreg = rep(c("linear","poisson","linear","poisson"), 2),
         interaction = rep(c(TRUE, FALSE), each = 4)) %>%
  mutate(mvar = if_else(mreg == "linear", "m_cont", "m_bin"),
         yvar = case_when(mreg == "linear"   & yreg == "linear"  ~ "y_cont_m_cont",
                          mreg == "logistic" & yreg == "linear"  ~ "y_cont_m_bin",
                          mreg == "linear"   & yreg == "poisson" ~ "y_pois_m_cont",
                          mreg == "logistic" & yreg == "poisson" ~ "y_pois_m_bin"),
         ## Fit regression models
         fit = pmap(list(mreg, yreg, interaction, yvar, mvar),
                    function(mreg, yreg, interaction, yvar, mvar) {
                      regmedint(data = demo2,
                                yvar = yvar, avar = "a", mvar = mvar, cvar = "c1", eventvar = NULL,
                                a0 = 0, a1 = 1, m_cde = 0, c_cond = 0,
                                mreg = mreg, yreg = yreg,
                                interaction = interaction, casecontrol = FALSE)
                    })) %>%
  mutate(data = map(fit, function(fit) {
    ## Re-evaluate at each c_cond value using the coef method.
    map(c_cond_grid, function(c_cond) {
      ## Force in a row tibble.
      as_tibble(t(c(c_cond = c_cond, coef(fit, c_cond = c_cond))))
    }) %>%
      ## Collect all rows in one tibble
      bind_rows()
  })) %>%
  select(-yvar, -fit, -mvar) %>%
  unnest(data) %>%
  ## Long format
  pivot_longer(cols = c(-mreg,-yreg,-interaction,-c_cond))

## Plot
res %>%
  filter(name %in% c("te","pnde","tnie")) %>%
  mutate(name = factor(name,
                       levels = c("te","pnde","tnie"),
                       labels = c("TE","PNDE","TNIE")),
         yreg = if_else(yreg == "linear", "linear", "non-linear")) %>%
  ggplot(mapping = aes(x = c_cond, y = value, group = name, linetype = name)) +
  geom_line() +
  scale_y_continuous(name = "Effect estimate (outcome model link function scale)") +
  scale_x_continuous(name = "Covariate value") +
  scale_linetype(name = "Effect") +
  facet_grid(interaction ~ mreg + yreg, scales = "free_y", labeller = label_both) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = "bottom",
        legend.key = element_blank(),
        plot.title = element_text(hjust = 0.5),
        strip.background = element_blank())
#+END_SRC
\normalsize

=mreg= refers to the mediator model specification (linear or logistic). =yreg= refers to the outcome model specification (linear or non-linear).\\

The following relationship between the effect estimates and covariate value can be observed.

|                      |        | mreg: linear | mreg: linear     | mreg: logistic | mreg: logistic   |
| Interaction          | Effect | yreg: linear | yreg: non-linear | yreg: linear   | yreg: non-linear |
|----------------------+--------+--------------+------------------+----------------+------------------|
| FALSE                | PNDE   | Constant     | Constant         | Constant       | Constant         |
| $(\theta_{3} = 0)$   | TNIE   | Constant     | Constant         | Varies         | Varies           |
|                      | TE     | Constant     | Constant         | Varies         | Varies           |
|                      |        |              |                  |                |                  |
| TRUE                 | PNDE   | Varies       | Varies           | Varies         | Varies           |
| $(\theta_{3} \ne 0)$ | TNIE   | Constant     | Constant         | Varies         | Varies           |
|                      | TE     | Varies       | Varies           | Varies         | Varies           |

The reasons for these specific covariate dependences can be understood by examing the PNDE and TNIE formulas in Section [[* Implementation of the regression-based causal mediation analysis method]]. Covariate dependence exists when the formula contains the term $\bbeta_{2}^{T}\bc$, which is the covariate part of linear predictor for the mediator model. If either one of PNDE and TNIE contains this term, TE (PNDE + TNIE) is also dependent on the covariates.\\

** Implications for marginal interpretation
These covariate-dependence of conditional natural effects have implications on whether and how marginal natural effects can be obtained with =regmedint=. In summary, only in the case of a linear mediator model and linear outcome model, one can obtain the marginal (population average) natural effects by evaluating the effect estimates at the mean covariate vector $E[\bC]$ (mean covariate vector in practice).

*** Linear mediator model, linear outcome model
In the case with a linear mediator model with a linear (Section [[* Linear mediator model, linear outcome model]]) outcome model, the PNDE (and also TNDE) formula contains the term $\bbeta_{2}^{T}\bc$. Notably PNDE (and also TNDE) is linear in the covariate vector $\bc$ as well as the counterfactual outcomes. Thus, evaluating this PNDE (and also TNDE) formula at the mean covariate vector $E[\bC]$ gives the marginal effect.

\begin{align*}
  \text{Conditional }PNDE
  &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc) \right\} (a_{1} - a_{0})\\
  \\
  \text{Marginal }PNDE
  &= E[Y_{a_{1},\uwave{M_{a_{0}}}}] - E[Y_{a_{0},\uwave{M_{a_{0}}}}]\\
  &~~~\text{By iterative expectation}\\
  &= E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] \right] -
     E \left[ E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\\
  &= E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\\
  &~~~\text{Inside is conditional PNDE at } \bC\\
  &= E\left[ \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC) \right\} (a_{1} - a_{0}) \right]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}E[\bC]) \right\} (a_{1} - a_{0})\\
  &\text{i.e., Equal to conditional PNDE formula evaluated at } E[\bC]\\
\end{align*}

When there is no treatment-mediator interaction term in the outcome model $(\theta_{3} = 0)$, the term $\bbeta_{2}^{T}\bc$ drops out of conditional PNDE formula. Only $\theta_{1}(a_{1} - a_{0})$ (treatment coefficient in the outcome model; also agrees with CDE) remains as the direct effect, thus, eliminating the covariate dependence. Under this modeling assumption of no treatment-mediator interaction term in the outcome model, the marginal effects are the same as the conditional effects because the latter do not vary across covariate patterns.

*** Linear mediator model, non-linear outcome model
In the case with a linear mediator model with a non-linear (Section [[* Linear mediator model, non-linear outcome model]]) outcome model, the PNDE (and also TNDE) formula contain the term $\bbeta_{2}^{T}\bc$. The PNDE (and also TNDE) formula is linear in the covariate vector $\bc$. However, the effect is defined on the outcome model link function scale (not linear in counterfactual outcomes). This non-linearity of the outcome model link function (logit in the example below) prevents the marginal interpretation of the conditional PNDE evaluated at $E[\bC]$. The interpretation of the effect evaluated at $E[\bC]$ is the /conditional/ effect for an /average individual/.

\begin{align*}
  \text{Conditional }PNDE
  &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc])\\
  &\approx \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc + \theta_{2}\sigma^{2}) \right\} (a_{1} - a_{0}) + \frac{1}{2} \theta_{3}^{2}\sigma^{2}(a_{1}^{2} - a_{0}^{2})\\
  \\
  \text{Marginal }PNDE
  &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}}]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}}])\\
  &~~~\text{By iterative expectation}\\
  &= \logit\left(E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] \right]\right) - \logit\left(E \left[ E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\right)\\
  &~~~\text{By non-linearity of outcome model link function}\\
  &\ne E \left[ \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC]) \right]\\
  &~~~\text{By the conditional PNDE formula}\\
  &\approx E \left[ \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC + \theta_{2}\sigma^{2}) \right\} (a_{1} - a_{0}) + \frac{1}{2} \theta_{3}^{2}\sigma^{2}(a_{1}^{2} - a_{0}^{2}) \right]\\
  &= \left\{ \theta_{1} + \theta_{3}(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}E[\bC] + \theta_{2}\sigma^{2}) \right\} (a_{1} - a_{0}) + \frac{1}{2} \theta_{3}^{2}\sigma^{2}(a_{1}^{2} - a_{0}^{2})\\
  &\text{i.e., Not equal not conditional PNDE formula evaluated at }E[\bC]\\
\end{align*}

When there is no treatment-mediator interaction term in the outcome model $(\theta_{3} = 0)$, the term $\bbeta_{2}^{T}\bc$ drops out of the conditional PNDE (and also TNDE) formula. Only $\theta_{1}(a_{1} - a_{0})$ (treatment coefficient in the outcome model; also agrees with CDE) remains as the direct effect, thus, eliminating the covariate dependence. Under this modeling assumption of no treatment-mediator interaction term in the outcome model, the marginal effects are the same as the conditional effects because the latter do not vary across covariate patterns.

*** Logistic mediator model, linear outcome model
In the case with a logistic mediator model with a linear (Section [[* Logistic mediator model, linear outcome model]]) outcome model, both the PNDE (and also TNDE) formula and the TNIE (and also PNIE) formula are non-linear functions of $\bbeta_{2}^{T}\bc$. Therefore, covariate dependence exists for both PNDE and TNIE. This non-linearity comes from the mediator model link function (logit). Because of this non-linearity, evaluation at $E[\bC]$ does not give a marginal interpretation. The interpretation the effect evaluated at $E[\bC]$ is the /conditional/ effect for an /average individual/. The PNDE is examined first.

\begin{align*}
  \text{Conditional }PNDE
  &= E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc]\\
  &= \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bc)}\\
  \\
  \text{Marginal }PNDE
  &= E[Y_{a_{1},\uwave{M_{a_{0}}}}] - E[Y_{a_{0},\uwave{M_{a_{0}}}}]\\
  &~~~\text{By iterative expectation}\\
  &= E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] \right] - E \left[ E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\\
  &= E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] - E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\\
  &~~~\text{Inside is conditional PNDE at }\bC\\
  &= E \left[ \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC)} \right]\\
  &= \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    E \left[ \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}\bC)} \right]\\
  &~~~\text{By non-linearity of mediator model link function}\\
  &\ne \left\{\theta_{1}(a_{1} - a_{0}) \right\} + \left\{\theta_{3}(a_{1} - a_{0}) \right\}
    \frac
    {    \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}E[\bC])}
    {1 + \exp(\beta_{0} + \beta_{1}\uwave{a_{0}} + \bbeta_{2}^{T}E[\bC])}\\
  &\text{i.e., Not equal not conditional PNDE formula evaluated at }E[\bC]\\
\end{align*}

The TNIE formula is examined below.

\begin{align*}
  \text{Conditional }TNIE
  &= E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc]\\
  &= (\theta_{2} + \theta_{3}\uwave{a_{1}})\left\{
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bc)}
    -
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bc)}
    \right\}\\
  \\
  \text{Marginal }TNIE
  &= E[Y_{\uwave{a_{1}},M_{a_{1}}}] - E[Y_{\uwave{a_{1}},M_{a_{0}}}]\\
  &~~~\text{By iterative expectation}\\
  &= E \left[ E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC] \right] - E \left[ E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC] \right]\\
  &= E \left[ E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC] - E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC] \right]\\
  &~~~\text{Inside is conditional TNIE at }\bC\\
  &= E \left[ (\theta_{2} + \theta_{3}\uwave{a_{1}})\left\{
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bC)}
    -
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bC)}
    \right\} \right]\\
  &= (\theta_{2} + \theta_{3}\uwave{a_{1}})\left\{
    E \left[ \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}\bC)} \right]
    -
    E \left[ \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bC)}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}\bC)} \right]
    \right\}\\
  &~~~\text{By non-linearity of mediator model link function}\\
  &\ne (\theta_{2} + \theta_{3}\uwave{a_{1}})\left\{
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}E[\bC])}
    {1 + \exp(\beta_{0} + \beta_{1}a_{1} + \bbeta_{2}^{T}E[\bC])}
    -
    \frac
    {    \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}E[\bC])}
    {1 + \exp(\beta_{0} + \beta_{1}a_{0} + \bbeta_{2}^{T}E[\bC])}
    \right\}\\
  &\text{i.e., Not equal not conditional TNIE formula evaluated at }E[\bC]\\
\end{align*}

When there is no treatment-mediator interaction term in the outcome model $(\theta_{3} = 0)$, the term $\bbeta_{2}^{T}\bc$ cancels out of the PNDE (and also TNDE) formulas. Only $\theta_{1}(a_{1} - a_{0})$ (treatment coefficient in the outcome model; also agrees with CDE) remains as the direct effect, thus, eliminating the covariate dependence for PNDE (and also TNDE). However, the TNIE (and also PNIE) formula remain as non-linear functions of $\bbeta_{2}^{T}\bc$, thus, covariate dependence persists for TNIE. Under this modeling assumption of no treatment-mediator interaction term in the outcome model, the marginal /direct/ effects are the same as the conditional direct effects because the latter do not vary across covariate patterns. However, the same does not hold for the /indirect/ effects.

*** Logistic mediator model, non-linear outcome model
In the cases with a logistic mediator model with a non-linear (Section [[* Logistic mediator model, non-linear outcome model]]) outcome model, both the PNDE (and also TNDE) formula and the TNIE (and also PNIE) formula are non-linear functions of $\bbeta_{2}^{T}\bc$. Therefore, covariate dependence exists for both PNDE and TNIE. This non-linearity comes from the mediator model link function (logit). Further, the effects are defined on the outcome model link function scale (not linear in counterfactual outcomes). Because of these non-linearity, evaluation at $E[\bC]$ does not give a marginal interpretation. The interpretation the effect evaluated at $E[\bC]$ is the /conditional/ effect for an /average individual/. The PNDE is examined first.

\begin{align*}
  \text{Conditional }PNDE
  &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC = \bc]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC = \bc])\\
  &\approx \theta_{1}(a_{1} - a_{0})\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bc))\\
  \\
  \text{Marginal }PNDE
  &= \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}}]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}}])\\
  &~~~\text{By iterative expectation}\\
  &= \logit\left(E \left[ E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC] \right]\right) - \logit\left(\left[ E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC] \right]\right)\\
  &~~~\text{By non-linearity of outcome model link function}\\
  &\ne E \left[ \logit(E[Y_{a_{1},\uwave{M_{a_{0}}}} | \bC]) - \logit(E[Y_{a_{0},\uwave{M_{a_{0}}}} | \bC]) \right]\\
  &\approx E[ \theta_{1}(a_{1} - a_{0})\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bC))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bC))]\\
  &= \theta_{1}(a_{1} - a_{0})\\
  &~~~ + E[\log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bC))]\\
  &~~~ - E[\log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^T\bC))]\\
  &~~~\text{By non-linearity of mediator model link function}\\
  &\ne \theta_{1}(a_{1} - a_{0})\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}a_{1} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^TE[\bC]))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}a_{0} + \beta_{0} + \beta_{1} \uwave{a_{0}} + \bbeta_{2}^TE[\bC]))\\
  &\text{i.e., Not equal not conditional PNDE formula evaluated at }E[\bC]\\
\end{align*}

The TNIE formula is examined below.

\begin{align*}
  \text{Conditional }TNIE
  &= \logit(E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC = \bc]) - \logit(E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC = \bc])\\
  &\approx \log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bc))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bc))\\
  \\
  \text{Marginal }TNIE
  &= \logit(E[Y_{\uwave{a_{1}},M_{a_{1}}}]) - \logit(E[Y_{\uwave{a_{1}},M_{a_{0}}}])\\
  &~~~\text{By iterative expectation}\\
  &= \logit\left(E\left[E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC]\right]\right) - \logit\left(E\left[E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC]\right]\right)\\
  &~~~\text{By non-linearity of outcome model link function}\\
  &\ne E \left[ \logit(E[Y_{\uwave{a_{1}},M_{a_{1}}} | \bC]) - \logit(E[Y_{\uwave{a_{1}},M_{a_{0}}} | \bC]) \right]\\
  &\approx E[\log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bC))\\
  &~~~ - \log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bC))\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bC))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bC))]\\
  &=     E[\log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bC))]\\
  &~~~ - E[\log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bC))]\\
  &~~~ + E[\log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^T\bC))]\\
  &~~~ - E[\log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^T\bC))]\\
  &~~~\text{By non-linearity of mediator model link function}\\
  &\ne   \log(1 + \exp(\beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^TE[\bC]))\\
  &~~~ - \log(1 + \exp(\beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^TE[\bC]))\\
  &~~~ + \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{1} + \bbeta_{2}^TE[\bC]))\\
  &~~~ - \log(1 + \exp(\theta_{2} + \theta_{3}\uwave{a_{1}} + \beta_{0} + \beta_{1} a_{0} + \bbeta_{2}^TE[\bC]))\\
  &\text{i.e., Not equal not conditional TNIE formula evaluated at }E[\bC]\\
\end{align*}

When there is no treatment-mediator interaction term in the outcome model $(\theta_{3} = 0)$, the term $\bbeta_{2}^{T}\bc$ cancels out of the PNDE (and also TNDE) expressions. Only $\theta_{1}(a_{1} - a_{0})$ (treatment coefficient in the outcome model; also agrees with CDE) remains as the direct effect, thus, eliminating the covariate dependence for PNDE (and also TNDE). However, the TNIE (and also PNIE) expressions remain as non-linear functions of $\bbeta_{2}^{T}\bc$, thus, covariate dependence persists for TNIE. Under this modeling assumption of no treatment-mediator interaction term in the outcome model, the marginal /direct/ effects are the same as the conditional direct effects because the latter do not vary across covariate patterns. However, the same does not hold for the /indirect/ effects.

** Practical implications for reporting
Evaluating the natural direct and indirect effects at the mean covariate level is the default behavior of the SAS macro cite:valeriMediationAnalysisAllowing2013. With the =regmedint= R package, the same can be done via setting the =c_cond= argument to the mean covariate vector.\\

The literature is somewhat confusing regarding when the effect estimates evaluated at the mean covariate vector have marginal interpretation. cite:valeriMediationAnalysisAllowing2013 (p139) states "For continuous outcomes, if C were set at its average level we would obtain marginal effects on the entire population." cite:vanderweeleExplanationCausalInference2015 (p37) states "\dots evaluated at the mean covariate levels are shown. For a continuous mediator, these effects will also be equal to the marginal effects on average for the population."\\

As shown above, both the mediator model and the outcome model have to be linear regression models. We outlined reasonable approaches to reporting in specific models below.

*** Linear mediator model, linear outcome model
Evaluation at the mean covariate vector gives the effect estimates marginal (population average) interpretation. Thus, reporting these marginal quantities for a well-defined population (set =c_cond= to the average in that population) is useful.\\

If there is no treatment-mediator interaction term in the outcome model, uniform conditional effects are implied and the marginal effects agree with the conditional effects.

*** Linear mediator model, non-linear outcome model
Evaluation at the mean covariate level does /not/ gives the effect estimates marginal (population average) interpretations. It is still possible to report the result evaluated at the mean covariate vector, however, the results should be interpreted as /conditional/ effects for an /average individual/. If categorical covariates (e.g., country) are involved, an average individual can be ambiguous or non-existent (e.g., individual residing in the average country). Reporting conditional effects evaluated at several meaningful covariate patterns may be preferred.\\

If there is no treatment-mediator interaction term in the outcome model, uniform conditional effects are implied and the marginal effects agree with the conditional effects.

*** Logistic mediator model, linear outcome model
Evaluation at the mean covariate level does /not/ gives the effect estimates marginal (population average) interpretations. It is still possible to report the result evaluated at the mean covariate vector, however, the results should be interpreted as /conditional/ effects for an /average individual/. If categorical covariates (e.g., country) are involved, an average individual can be ambiguous or non-existent (e.g., individual residing in the average country). Reporting conditional effects evaluated at several meaningful covariate patterns may be preferred.\\

The same is true even if there is no treatment-mediator interaction term in the outcome model.

*** Logistic mediator model, non-linear outcome model
Evaluation at the mean covariate level does /not/ gives the effect estimates marginal (population average) interpretations. It is still possible to report the result evaluated at the mean covariate vector, however, the results should be interpreted as /conditional/ effects for an /average individual/. If categorical covariates (e.g., country) are involved, an average individual can be ambiguous or non-existent (e.g., individual residing in the average country). Reporting conditional effects evaluated at several meaningful covariate patterns may be preferred.\\

The same is true even if there is no treatment-mediator interaction term in the outcome model.


* Bibliography
\renewcommand{\section}[2]{}
# Following lines must be left-aligned without preceding spaces.
bibliographystyle:apalike
bibliography:~/.emacs.d/misc/zotero.bib
